variables = {}

variables["5j_ge3t"] = [
    "Evt_aplanarity",
    "Evt_CSV_dev",
    "RecoZ_BJet1_Pt",
    "Reco_JABDT_ttH_log_tophad_pt",
    "Evt_M2_minDrJets",
    "RecoTTZ_TopHad_W_Pt",
    "RecoHiggs_Chi2",
    "RecoZ_Chi2",
    "Evt_Pt_minDrTaggedJets",
    "RecoZ_M",
    "RecoZ_Pt",
    "Evt_sphericity_jets",
    "Reco_JABDT_ttH_Jet_CSV_btoplep",
    "RecoHiggs_BJet1_Eta",
    "Evt_Dr_minDrLepJet",
    "Evt_Pt_minDrJets",
    "Evt_M3",
    "Jet_Pt[0]",
    "TaggedJet_E[0]",
    "RecoHiggs_M",
    "Evt_M2_TaggedJetsAverage",
    "Evt_HT_wo_MET",
    "Evt_HT_tags",
    "Reco_ttH_whaddau_m2",
    "RecoZ_Deta",
    "RecoHiggs_M_log",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_blr",
    "RecoZ_Chi2_log",
    "RecoHiggs_Chi2_log",
    ]


variables["ge6j_ge3t"] = [
    "Evt_aplanarity",
    "RecoTTZ_Dphi_Z_bHad",
    "RecoHiggs_Pt",
    "Evt_h2",
    "N_BTagsL",
    "Reco_JABDT_ttH_log_toplep_pt",
    "RecoTTZ_Deta_Z_Lep",
    "RecoTTZ_Z_M_log",
    "Evt_M2_closestTo91TaggedJets",
    "RecoHiggs_E",
    "Evt_blr_transformed",
    "Evt_CSV_min",
    "RecoZ_Deta",
    "RecoTTZ_Deta_Lep_bHad",
    "TaggedJet_M[0]",
    "CSV[2]",
    "Evt_blr",
    "Reco_ttH_h_m",
    "Jet_Pt[0]",
    "RecoTTH_Higgs_M_log",
    "Evt_CSV_avg",
    "RecoHiggs_Chi2_log",
    "Evt_Dr_TaggedJetsAverage",
    "RecoTTZ_Chi2Z_log",
    "Evt_M2_TaggedJetsAverage",
    "RecoTTH_Chi2Higgs_log",
    "RecoZ_Chi2_log",
    "Evt_Deta_TaggedJetsAverage",
    "Reco_JABDT_ttH_log_h_m",
    "Reco_ttH_bestJABDToutput",
    ]


variables["4j_ge3t"] = [
    "Evt_Dr_maxDrTaggedJets",
    "Evt_h3",
    "Evt_Dr_minDrLepJet",
    "TaggedJet_Eta[3]",
    "Evt_HT_tags",
    "RecoZ_Chi2",
    "RecoZ_Dr",
    "Evt_MHT",
    "Evt_Pt_minDrTaggedJets",
    "Evt_Dr_minDrJets",
    "Evt_M2_closestTo91TaggedJets",
    "RecoTTZ_TopLep_M",
    "Reco_ttH_tophad_m",
    "Reco_ttH_hdau_idx2",
    "TaggedJet_Pt[0]",
    "TaggedJet_M[3]",
    "Reco_ttH_whad_eta",
    "RecoTTZ_Chi2TopLep",
    "RecoZ_BJet1_Pt",
    "Evt_blr",
    "RecoZ_M",
    "RecoTTZ_TopHad_W_Eta",
    "RecoZ_BJet1_M",
    "Reco_WLep_Phi",
    "RecoTTZ_Chi2WHad_log",
    "CSV[1]",
    "RecoZ_M_log",
    "RecoHiggs_Chi2",
    "RecoHiggs_Chi2_log",
    "RecoZ_Chi2_log",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
