variables = {}

variables["4j_ge3t"] = [
    "CSV[2]",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_M2_TaggedJetsAverage",
    "Evt_M3",
    "Evt_MHT",
    "Evt_MTW",
    "Evt_M_TaggedJetsAverage",
    "Evt_Pt_minDrJets",
    "Evt_Pt_minDrTaggedJets",
    "Evt_blr_transformed",
    "RecoHiggs_BJet2_Pt",
    "RecoHiggs_Chi2",
    "RecoHiggs_Chi2_log",
    "RecoHiggs_M",
    "RecoTTZ_Chi2TopHad",
    "RecoTTZ_Chi2Total",
    "RecoTTZ_Chi2Total_log",
    "RecoTTZ_Chi2WHad",
    "RecoTTZ_Deta_bLep_bHad",
    "RecoTTZ_Deta_bLep_topHad",
    "RecoTTZ_TopHad_M",
    "RecoTTZ_TopHad_Pt",
    "RecoTTZ_TopHad_W_M",
    "RecoTTZ_TopLep_BJet_Pt",
    "RecoTTZ_TopLep_W_M",
    "RecoZ_BJet2_Pt",
    "RecoZ_Chi2",
    "RecoZ_Chi2_log",
    "RecoZ_M_log",
    "RecoZ_Pt",
    ]


variables["5j_ge3t"] = [
    "CSV[2]",
    "CSV[3]",
    "Evt_CSV_dev",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_Dr_JetsAverage",
    "Evt_M2_TaggedJetsAverage",
    "Evt_M3_oneTagged",
    "Evt_M_TaggedJetsAverage",
    "Evt_Pt_minDrTaggedJets",
    "Evt_blr_transformed",
    "RecoHiggs_BJet2_Pt",
    "RecoHiggs_Chi2_log",
    "RecoHiggs_M",
    "RecoHiggs_M_log",
    "RecoTTZ_Chi2Total",
    "RecoTTZ_Chi2Total_log",
    "RecoTTZ_Chi2WHad_log",
    "RecoTTZ_TopHad_M",
    "RecoTTZ_TopHad_Pt",
    "RecoTTZ_TopHad_W_M",
    "RecoTTZ_TopHad_W_Pt",
    "RecoTTZ_TopLep_M",
    "RecoTTZ_TopLep_W_M",
    "RecoZ_BJet1_M",
    "RecoZ_BJet2_Pt",
    "RecoZ_Chi2",
    "RecoZ_Chi2_log",
    "RecoZ_M",
    "RecoZ_M_log",
    "RecoZ_Pt",
    ]


variables["ge6j_ge3t"] = [
    "CSV[2]",
    "CSV[3]",
    "Evt_CSV_dev",
    "Evt_Deta_JetsAverage",
    "Evt_Deta_TaggedJetsAverage",
    #"Evt_Dr_closestTo91TaggedJets",
    "Evt_M2_TaggedJetsAverage",
    "Evt_Pt_minDrTaggedJets",
    "Evt_blr",
    "Evt_blr_transformed",
    "RecoHiggs_BJet2_Pt",
    "RecoHiggs_Chi2",
    "RecoHiggs_Chi2_log",
    "RecoHiggs_M_log",
    "RecoTTZ_Chi2Total_log",
    "RecoTTZ_Chi2WHad",
    "RecoTTZ_Chi2Z",
    "RecoTTZ_Chi2Z_log",
    "RecoTTZ_TopHad_W_M",
    "RecoTTZ_TopLep_W_M",
    "RecoTTZ_Z_BJet1_Pt",
    "RecoTTZ_Z_BJet2_Pt",
    "RecoTTZ_Z_M",
    "RecoTTZ_Z_M_log",
    "RecoTTZ_Z_Pt",
    "RecoZ_BJet2_Pt",
    "RecoZ_Chi2",
    "RecoZ_Chi2_log",
    "RecoZ_M",
    "RecoZ_M_log",
    ]


variables["ge4j_ge4t"] = [
    #"Evt_blr",
    #"Evt_M_TaggedJetsAverage",
    #"Evt_M2_TaggedJetsAverage",
    ##"Evt_Dr_minDrLepTag",
    #"Evt_Dr_TaggedJetsAverage",
    #"Evt_E_JetsAverage",
    #"Evt_Pt_TaggedJetsAverage",
    #"Jet_Pt[0]",
    #"Evt_CSV_avg_tagged",
    #"N_LooseJets",
    #"Evt_CSV_avg",
    #"CSV[3]",
    #"Evt_h0",
    "Evt_MTW",
    "TaggedJet_Pt[3]",
    "CSV[1]",
    "Evt_Deta_TaggedJetsAverage",
    #"Evt_M2_closestTo91TaggedJets",
    "Evt_blr_transformed",
    "CSV[2]",
    
    ##"CSV[2]",
    ##"CSV[3]",
    #"Evt_CSV_dev",
    #"Evt_CSV_avg",
    #"Evt_Deta_TaggedJetsAverage",
    ##"Evt_Dr_JetsAverage",
    #"Evt_M2_TaggedJetsAverage",
    ##"Evt_M3_oneTagged",
    #"Evt_M_TaggedJetsAverage",
    #"Evt_Pt_minDrTaggedJets",
    #"Evt_HT_jets",
    ##"Evt_blr_transformed",
    #"Evt_blr",
    
    "RecoHiggs_cosdTheta",
    "RecoZ_BJet1_E",
    "RecoZ_M_log",
    "RecoTTZ_TopLep_Pt",
    "RecoZ_Dphi",
    "RecoHiggs_M_log",
    "RecoTTZ_TopHad_W_Pt",
    "RecoZ_Pt",
    "RecoTTZ_Deta_bLep_topHad",
    "RecoZ_M",
    "RecoHiggs_Dr",
    "RecoTTZ_Chi2Total_log",
    "RecoZ_BJet1_M",
    "RecoZ_Chi2",
    "RecoTTZ_Dphi_topLep_topHad",
    "RecoHiggs_Chi2",
    "RecoZ_BJet2_Pt",
    "RecoTTZ_TopLep_W_M",
    "RecoHiggs_Chi2_log",
    "RecoZ_Chi2_log",
    ]


variables["ge4j_3t"] = [
    #"Evt_Pt_JetsAverage",
    #"Evt_M3",
    #"Evt_CSV_dev",
    #"Evt_M_Total",
    #"Evt_M_TaggedJetsAverage",
    #"TaggedJet_Pt[2]",
    #"Evt_HT",
    ##"Evt_M2_closestTo91TaggedJets",
    #"Evt_HT_wo_MET",
    ##"Evt_M2_closestTo125TaggedJets",
    #"Evt_Deta_JetsAverage",
    #"Evt_HT_jets",
    #"Evt_CSV_min_tagged",
    "Evt_M2_TaggedJetsAverage",
    "Evt_CSV_avg_tagged",
    "CSV[2]",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_CSV_avg",
    "Evt_blr_transformed",
    "Evt_Pt_minDrTaggedJets",
    
    ##"CSV[2]",
    ##"CSV[3]",
    #"Evt_CSV_dev",
    #"Evt_CSV_avg",
    #"Evt_Deta_TaggedJetsAverage",
    ##"Evt_Dr_JetsAverage",
    #"Evt_M2_TaggedJetsAverage",
    ##"Evt_M3_oneTagged",
    #"Evt_M_TaggedJetsAverage",
    #"Evt_Pt_minDrTaggedJets",
    ##"Evt_blr_transformed",
    #"Evt_blr",
    #"Evt_HT_jets",
    
    "RecoTTZ_Deta_bLep_bHad",
    "RecoHiggs_M",
    "RecoTTZ_TopLep_BJet_Pt",
    "RecoTTZ_Chi2Total",
    "RecoTTZ_Deta_bLep_topHad",
    "RecoZ_Chi2",
    "RecoZ_Pt",
    "RecoZ_M_log",
    "RecoHiggs_BJet2_Pt",
    "RecoZ_BJet2_Pt",
    "RecoTTZ_Chi2TopHad",
    "RecoHiggs_Chi2",
    "RecoTTZ_TopHad_Pt",
    "RecoZ_Chi2_log",
    "RecoHiggs_Chi2_log",
    "RecoTTZ_TopHad_W_M",
    "RecoTTZ_Chi2WHad",
    "RecoTTZ_TopLep_W_M",
    "RecoTTZ_TopHad_M",
    "RecoTTZ_Chi2Total_log",
    ]


all_variables = list(set( [v for key in variables for v in variables[key] ] ))
