variables = {}

variables["5j_ge3t"] = [
    "Reco_JABDT_ttH_log_tophad_pt",
    "Reco_ttH_hdau_idx2",
    "Evt_HT",
    "RecoZ_BJet2_Pt",
    "Jet_Pt[0]",
    "Jet_E[0]",
    "Evt_CSV_avg",
    "RecoZ_BJet1_M",
    "Reco_WLep_Pt",
    "Evt_Deta_JetsAverage",
    "Jet_Pt[3]",
    "Reco_JABDT_ttH_Jet_CSV_btophad",
    "TaggedJet_CSV[0]",
    "RecoTTZ_Chi2WHad_log",
    "Reco_JABDT_ttH_Jet_CSV_whaddau1",
    "Evt_h1",
    "Evt_M_TaggedJetsAverage",
    "RecoZ_Chi2",
    "Evt_M2_TaggedJetsAverage",
    "Evt_blr",
    "Evt_Dr_JetsAverage",
    "Evt_MHT",
    "Evt_CSV_dev",
    "RecoZ_Chi2_log",
    "CSV[3]",
    "CSV[2]",
    "Evt_Deta_TaggedJetsAverage",
    "RecoTTZ_Chi2Total_log",
    "RecoHiggs_Chi2_log",
    "Evt_blr_transformed",
    ]


variables["ge6j_ge3t"] = [
    "Evt_CSV_dev_tagged",
    "RecoTTH_Chi2Higgs_log",
    "Evt_CSV_avg_tagged",
    "Evt_Pt_minDrTaggedJets",
    "Reco_WLep_Pt",
    "Evt_h1",
    "RecoTTZ_Chi2Z",
    "RecoTTZ_Z_M_log",
    "Jet_Pt[1]",
    "RecoTTZ_Chi2Z_log",
    "Reco_JABDT_ttH_log_h_m",
    "TaggedJet_CSV[3]",
    "Evt_MHT",
    "RecoZ_BJet2_Pt",
    "Evt_CSV_avg",
    "Jet_Pt[5]",
    "Reco_JABDT_ttH_Jet_CSV_hdau2",
    "Evt_M2_TaggedJetsAverage",
    "Evt_CSV_min_tagged",
    "CSV[4]",
    "Evt_CSV_dev",
    "Reco_JABDT_ttH_Jet_CSV_hdau1",
    "RecoZ_Chi2_log",
    "Evt_blr",
    "CSV[3]",
    "RecoHiggs_Chi2_log",
    "Evt_Deta_TaggedJetsAverage",
    "Reco_ttH_bestJABDToutput",
    "CSV[2]",
    "Evt_blr_transformed",
    ]


variables["4j_ge3t"] = [
    "RecoTTZ_Chi2Total",
    "TaggedJet_Pt[2]",
    "RecoTTZ_Chi2TopHad_log",
    "Reco_ttH_whaddau_phi1",
    "RecoZ_Chi2",
    "Reco_JABDT_ttH_log_h_m",
    "RecoTTZ_TopHad_W_M",
    "Reco_JABDT_ttH_Jet_CSV_hdau1",
    "RecoTTZ_TopLep_W_M",
    "Evt_Deta_JetsAverage",
    "RecoTTZ_Chi2TopHad",
    "RecoHiggs_Chi2",
    "TaggedJet_CSV[0]",
    "Evt_M2_TaggedJetsAverage",
    "RecoTTZ_Chi2WHad",
    "Evt_CSV_min",
    "Reco_WLep_Mass",
    "CSV[3]",
    "RecoTTZ_TopHad_Pt",
    "Evt_CSV_dev",
    "Jet_Pt[3]",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_Pt_minDrTaggedJets",
    "RecoHiggs_Chi2_log",
    "CSV[2]",
    "RecoTTZ_TopHad_M",
    "RecoZ_Chi2_log",
    "Evt_blr_transformed",
    "Evt_MHT",
    "RecoTTZ_Chi2Total_log",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
