variables = {}

variables["ge4j_3t"] = [
    "Evt_M_TaggedJetsAverage",
    "Evt_M_JetsAverage",
    "Evt_CSV_avg_tagged",
    "Evt_M2_minDrJets",
    "Evt_Dr_TaggedJetsAverage",
    "Evt_M2_JetsAverage",
    "Evt_HT_jets",
    "Evt_HT",
    "Evt_Pt_minDrJets",
    "Jet_Pt[0]",
    "Evt_Dr_minDrTaggedJets",
    "Evt_HT_wo_MET",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_M_Total",
    "Evt_CSV_avg",
    "Evt_M2_TaggedJetsAverage",
    "Evt_M2_minDrTaggedJets",
    "Evt_Pt_minDrTaggedJets",
    "Evt_M2_closestTo91TaggedJets",
    "Evt_M2_closestTo125TaggedJets",
    ]


variables["5j_ge3t"] = [
    "Evt_Dr_maxDrJets",
    "Evt_M_JetsAverage",
    "Evt_Dr_JetsAverage",
    "CSV[2]",
    "Evt_aplanarity",
    "Evt_M2_JetsAverage",
    "Jet_Pt[0]",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M_Total",
    "Evt_M2_TaggedJetsAverage",
    "Evt_HT",
    "Evt_HT_wo_MET",
    "Evt_M2_minDrJets",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_Pt_minDrJets",
    "Evt_Pt_minDrTaggedJets",
    "Evt_Dr_closestTo91TaggedJets",
    "Evt_M2_minDrTaggedJets",
    "Evt_M2_closestTo91TaggedJets",
    "Evt_M2_closestTo125TaggedJets",
    ]


variables["ge6j_ge3t"] = [
    "Evt_M_TaggedJetsAverage",
    "Jet_Pt[4]",
    "Evt_HT_wo_MET",
    "Evt_HT_tags",
    "N_BTagsM",
    "Evt_h2",
    "Jet_M[0]",
    "Jet_Pt[0]",
    "CSV[2]",
    "Evt_Dr_minDrTaggedJets",
    "Evt_Dr_TaggedJetsAverage",
    "Evt_CSV_avg",
    "Evt_M_Total",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_M2_TaggedJetsAverage",
    "Evt_Dr_closestTo91TaggedJets",
    "Evt_M2_minDrTaggedJets",
    "Evt_Pt_minDrTaggedJets",
    "Evt_M2_closestTo125TaggedJets",
    "Evt_M2_closestTo91TaggedJets",
    ]


variables["ge4j_ge4t"] = [
    "Evt_CSV_avg",
    "Jet_Pt[0]",
    "Evt_HT_tags",
    "Evt_M_TaggedJetsAverage",
    "Evt_Pt_TaggedJetsAverage",
    "Evt_Pt_minDrJets",
    "Evt_Dr_minDrJets",
    "Evt_E_TaggedJetsAverage",
    "Evt_M2_TaggedJetsAverage",
    "Evt_M2_minDrJets",
    "Evt_HT_wo_MET",
    "Evt_M_Total",
    "Evt_HT",
    "Evt_Dr_TaggedJetsAverage",
    "Evt_Dr_minDrTaggedJets",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_M2_minDrTaggedJets",
    "Evt_Pt_minDrTaggedJets",
    "Evt_M2_closestTo91TaggedJets",
    "Evt_M2_closestTo125TaggedJets",
    ]


variables["4j_ge3t"] = [
    "Evt_transverse_sphericity",
    "Evt_Dr_minDrLepJet",
    "TaggedJet_E[0]",
    "Evt_MHT",
    "CSV[1]",
    "Evt_Dr_JetsAverage",
    "Evt_Dr_TaggedJetsAverage",
    "Evt_aplanarity",
    "Evt_Pt_TaggedJetsAverage",
    "Evt_M2_JetsAverage",
    "Evt_M2_TaggedJetsAverage",
    "Evt_Pt_minDrTaggedJets",
    "Evt_Pt_minDrJets",
    "Evt_HT_wo_MET",
    "Evt_Dr_minDrJets",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_M2_minDrJets",
    "Evt_M2_minDrTaggedJets",
    "Evt_M2_closestTo125TaggedJets",
    "Evt_M2_closestTo91TaggedJets",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
