variables = {}

variables["ge4j_3t"] = [
    "Evt_h1",
    "Evt_M2_closestTo91TaggedJets",
    "CSV[3]",
    "RecoZ_Chi2",
    "Evt_Pt_minDrTaggedJets",
    "Evt_M_Total",
    "Evt_M2_closestTo125TaggedJets",
    "RecoHiggs_M",
    "Evt_Pt_minDrJets",
    "Evt_Dr_TaggedJetsAverage",
    "RecoZ_M_log",
    "RecoZ_Pt",
    "RecoHiggs_M_log",
    "Jet_Pt[0]",
    "RecoHiggs_Chi2",
    "Evt_M2_TaggedJetsAverage",
    "Evt_CSV_avg",
    "Evt_Deta_TaggedJetsAverage",
    "RecoHiggs_Chi2_log",
    "RecoZ_Chi2_log",
    ]


variables["5j_ge3t"] = [
    "Evt_M3_oneTagged",
    "Evt_Dr_JetsAverage",
    "CSV[1]",
    "Evt_Pt_minDrTaggedJets",
    "RecoZ_BJet1_Pt",
    "RecoTTZ_Chi2Total_log",
    "RecoZ_M",
    "RecoHiggs_Pt",
    "RecoZ_Chi2",
    "Evt_M2_TaggedJetsAverage",
    "Evt_M2_minDrTaggedJets",
    "Evt_Pt_minDrJets",
    "RecoZ_M_log",
    "Evt_blr",
    "RecoHiggs_M",
    "RecoHiggs_M_log",
    "RecoHiggs_Chi2",
    "Evt_Deta_TaggedJetsAverage",
    "RecoHiggs_Chi2_log",
    "RecoZ_Chi2_log",
    ]


variables["ge6j_ge3t"] = [
    "RecoTTZ_Deta_Z_Lep",
    "Evt_Pt_minDrTaggedJets",
    "RecoHiggs_M",
    "RecoTTZ_Chi2Total_log",
    "RecoHiggs_M_log",
    "RecoHiggs_Chi2",
    "RecoTTH_Chi2Higgs",
    "Evt_Dr_TaggedJetsAverage",
    "Jet_Pt[0]",
    "Evt_blr",
    "RecoTTH_Higgs_M_log",
    "CSV[2]",
    "RecoTTZ_Chi2Z",
    "RecoTTZ_Z_M_log",
    "Evt_Deta_TaggedJetsAverage",
    "RecoHiggs_Chi2_log",
    "Evt_CSV_avg",
    "RecoTTZ_Chi2Z_log",
    "RecoTTH_Chi2Higgs_log",
    "RecoZ_Chi2_log",
    ]


variables["ge4j_ge4t"] = [
    "Evt_Pt_minDrJets",
    "Evt_Dr_TaggedJetsAverage",
    "RecoZ_BJet1_Pt",
    "Evt_M2_minDrTaggedJets",
    "Evt_h2",
    "RecoHiggs_Pt",
    "Evt_M2_minDrJets",
    "RecoZ_Pt",
    "RecoHiggs_M",
    "Evt_Pt_minDrTaggedJets",
    "RecoZ_BJet2_Pt",
    "RecoZ_M",
    "Evt_M2_closestTo91TaggedJets",
    "RecoZ_M_log",
    "RecoHiggs_M_log",
    "Evt_Deta_TaggedJetsAverage",
    "RecoHiggs_Chi2_log",
    "RecoZ_Chi2",
    "RecoZ_Chi2_log",
    "RecoHiggs_Chi2",
    ]


variables["4j_ge3t"] = [
    "RecoHiggs_Dr",
    "Evt_M_TaggedJetsAverage",
    "N_BTagsM",
    "RecoZ_BJet1_M",
    "Evt_Dr_TaggedJetsAverage",
    "Jet_M[3]",
    "Evt_E_TaggedJetsAverage",
    "RecoZ_Pt",
    "Evt_Deta_TaggedJetsAverage",
    "RecoTTZ_Deta_Lep_topHad",
    "Evt_Dr_maxDrTaggedJets",
    "RecoHiggs_M",
    "RecoHiggs_M_log",
    "Evt_Pt_minDrTaggedJets",
    "RecoHiggs_Chi2",
    "RecoZ_Chi2",
    "RecoTTZ_Chi2TopHad_log",
    "RecoTTZ_Chi2WHad_log",
    "RecoHiggs_Chi2_log",
    "RecoZ_Chi2_log",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
