variables = {}

variables["ge4j_3t"] = [
    "Evt_aplanarity",
    "Evt_Eta_TaggedJetsAverage",
    "Evt_transverse_sphericity_tags",
    "Evt_Deta_maxDetaTagTag",
    "RecoHiggs_Deta",
    "RecoTTZ_Deta_Lep_bHad",
    "RecoTTZ_Dphi_bHad_wHad",
    "RecoTTZ_Dphi_bLep_wLep",
    "RecoHiggs_Dphi",
    "Evt_aplanarity_jets",
    "Evt_Dr_maxDrTaggedJets",
    "Evt_sphericity",
    "RecoTTZ_cosdTheta_bHad_wHad",
    "Evt_transverse_sphericity_jets",
    "Evt_Dr_minDrTaggedJets",
    "RecoZ_Dphi",
    "Evt_sphericity_tags",
    "Evt_Deta_maxDetaJetJet",
    "Evt_Dr_minDrLepJet",
    "RecoZ_Dr",
    "Evt_sphericity_jets",
    "RecoHiggs_Dr",
    "Evt_Dr_minDrLepTag",
    "RecoTTZ_Dphi_topLep_topHad",
    "Evt_Dr_TaggedJetsAverage",
    "Evt_Dr_maxDrJets",
    "Evt_Dr_minDrJets",
    "Evt_Dr_JetsAverage",
    "Evt_Deta_JetsAverage",
    "Evt_Deta_TaggedJetsAverage",
    ]


variables["5j_ge3t"] = [
    "Evt_Deta_maxDetaJetTag",
    "Evt_Dr_minDrJets",
    "RecoTTZ_cosdTheta_Lep_bHad",
    "RecoTTZ_cosdTheta_topLep_topHad",
    "RecoZ_cosdTheta",
    "RecoTTZ_Deta_Lep_topHad",
    "Evt_aplanarity_jets",
    "RecoHiggs_Deta",
    "RecoTTZ_cosdTheta_bLep_bHad",
    "RecoTTZ_Dphi_bLep_bHad",
    "RecoZ_Dphi",
    "Evt_Deta_maxDetaTagTag",
    "Evt_transverse_sphericity",
    "Evt_aplanarity",
    "RecoTTZ_Deta_bLep_bHad",
    "Evt_sphericity_jets",
    "Evt_Eta_JetsAverage",
    "Evt_sphericity",
    "Evt_Dr_maxDrJets",
    "RecoTTZ_cosdTheta_Lep_topHad",
    "RecoHiggs_Dr",
    "RecoZ_Dr",
    "Evt_aplanarity_tags",
    "Evt_Dr_minDrLepTag",
    "Evt_Dr_JetsAverage",
    "Evt_Deta_JetsAverage",
    "Evt_Dr_minDrTaggedJets",
    "Evt_Dr_TaggedJetsAverage",
    "Evt_Dr_maxDrTaggedJets",
    "Evt_Deta_TaggedJetsAverage",
    ]


variables["ge6j_ge3t"] = [
    "RecoTTZ_cosdTheta_Z_Lep",
    "Evt_transverse_sphericity",
    "Evt_aplanarity_jets",
    "RecoTTZ_cosdTheta_bHad_wHad",
    "RecoTTZ_Deta_Z_bLep",
    "RecoZ_cosdTheta",
    "Evt_sphericity",
    "RecoTTZ_cosdTheta_Lep_topHad",
    "RecoTTZ_Dphi_topLep_topHad",
    "RecoTTZ_Deta_bLep_bHad",
    "RecoZ_Dphi",
    "Evt_Eta_JetsAverage",
    "Evt_Dr_maxDrJets",
    "Evt_Deta_maxDetaTagTag",
    "RecoHiggs_Dr",
    "RecoTTZ_Dphi_Z_topLep",
    "RecoTTZ_Deta_Z_Lep",
    "RecoTTZ_Deta_Z_bHad",
    "RecoTTZ_cosdTheta_Z_bHad",
    "RecoTTZ_Deta_Lep_topHad",
    "RecoHiggs_Dphi",
    "Evt_sphericity_jets",
    "Evt_Deta_JetsAverage",
    "RecoZ_Dr",
    "Evt_Dr_minDrLepTag",
    "Evt_aplanarity_tags",
    "Evt_Dr_minDrTaggedJets",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_Dr_maxDrTaggedJets",
    "Evt_Dr_TaggedJetsAverage",
    ]


variables["ge4j_ge4t"] = [
    "Evt_sphericity_tags",
    "RecoTTZ_Deta_bHad_wHad",
    "RecoTTZ_Dphi_bLep_wLep",
    "RecoTTZ_Deta_topLep_topHad",
    "RecoTTZ_cosdTheta_bHad_wHad",
    "Jet_Eta[3]",
    "Evt_aplanarity",
    "RecoTTZ_Deta_topHad_wLep",
    "Evt_transverse_sphericity_jets",
    "Evt_transverse_sphericity",
    "Evt_Deta_maxDetaJetJet",
    "Evt_Dr_minDrLepJet",
    "RecoTTZ_cosdTheta_topLep_bHad",
    "RecoTTZ_cosdTheta_topHad_wLep",
    "RecoZ_BJet2_Eta",
    "Evt_Eta_TaggedJetsAverage",
    "RecoZ_Deta",
    "Evt_Dr_TaggedJetsAverage",
    "Evt_sphericity_jets",
    "RecoTTZ_Deta_bLep_topHad",
    "Evt_Dr_JetsAverage",
    "RecoZ_Dr",
    "Evt_Dr_minDrTaggedJets",
    "Evt_Eta_JetsAverage",
    "Evt_Deta_JetsAverage",
    "Evt_Deta_maxDetaJetTag",
    "Evt_Dr_maxDrJets",
    "RecoZ_Dphi",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_Dr_minDrJets",
    ]


variables["4j_ge3t"] = [
    "RecoTTZ_Deta_Lep_bHad",
    "Evt_transverse_sphericity_tags",
    "RecoTTZ_Dphi_topHad_wLep",
    "Evt_sphericity_tags",
    "RecoTTZ_Deta_bLep_topHad",
    "RecoTTZ_Deta_topHad_wLep",
    "RecoTTZ_cosdTheta_topLep_bHad",
    "RecoTTZ_cosdTheta_Lep_topHad",
    "RecoZ_Dphi",
    "Evt_sphericity_jets",
    "Evt_aplanarity_tags",
    "Evt_transverse_sphericity_jets",
    "Evt_aplanarity",
    "RecoTTZ_Dphi_Lep_topHad",
    "RecoTTZ_Deta_topLep_topHad",
    "RecoHiggs_Dr",
    "Evt_sphericity",
    "RecoTTZ_cosdTheta_bHad_wHad",
    "Evt_Deta_maxDetaTagTag",
    "Evt_Deta_JetsAverage",
    "Evt_Dr_minDrJets",
    "RecoTTZ_Dphi_bHad_wHad",
    "RecoZ_Dr",
    "Evt_Dr_maxDrJets",
    "Evt_Dr_minDrLepTag",
    "Evt_Dr_JetsAverage",
    "Evt_Dr_minDrTaggedJets",
    "Evt_Dr_maxDrTaggedJets",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_Dr_TaggedJetsAverage",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
