variables = {}
variables["ge6j_ge3t"] = [
    'CSV[0]',
    'CSV[1]',
    'CSV[2]',
    'CSV[3]',
    'Jet_DeepCSV_b[0]',
    'Jet_DeepCSV_b[1]',
    'Jet_DeepCSV_b[2]',
    'Jet_DeepCSV_b[3]',
    'Jet_DeepCSV_bb[0]',
    'Jet_DeepCSV_bb[1]',
    'Jet_DeepCSV_bb[2]',
    'Jet_DeepCSV_bb[3]',
    'Jet_DeepCSV_c[0]',
    'Jet_DeepCSV_c[1]',
    'Jet_DeepCSV_c[2]',
    'Jet_DeepCSV_c[3]',
    'Jet_DeepCSV_udsg[0]',
    'Jet_DeepCSV_udsg[1]',
    'Jet_DeepCSV_udsg[2]',
    'Jet_DeepCSV_udsg[3]',
    'Jet_E[0]',
    'Jet_E[1]',
    'Jet_E[2]',
    'Jet_E[3]',
    'Jet_Eta[0]',
    'Jet_Eta[1]',
    'Jet_Eta[2]',
    'Jet_Eta[3]',
    'Jet_M[0]',
    'Jet_M[1]',
    'Jet_M[2]',
    'Jet_M[3]',
    'Jet_Phi[0]',
    'Jet_Phi[1]',
    'Jet_Phi[2]',
    'Jet_Phi[3]',
    'Jet_Pt[0]',
    'Jet_Pt[1]',
    'Jet_Pt[2]',
    'Jet_Pt[3]',
    'LooseLepton_E[0]',
    'LooseLepton_Eta[0]',
    'LooseLepton_Phi[0]',
    'LooseLepton_Pt[0]',
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))

