variables = {}

variables["ge4j_ge3t"] = [
    'CSV[0]',
    'CSV[1]',
    'CSV[2]',
    'CSV[3]',

    #'Jet_DeepJetCSV[0]',
    #'Jet_DeepJetCSV[1]',
    #'Jet_DeepJetCSV[2]',
    #'Jet_DeepJetCSV[3]',
    #'Jet_DeepJet_b[0]',
    #'Jet_DeepJet_b[1]',
    #'Jet_DeepJet_b[2]',
    #'Jet_DeepJet_b[3]',
    #'Jet_DeepJet_bb[0]',
    #'Jet_DeepJet_bb[1]',
    #'Jet_DeepJet_bb[2]',
    #'Jet_DeepJet_bb[3]',
    #'Jet_DeepJet_c[0]',
    #'Jet_DeepJet_c[1]',
    #'Jet_DeepJet_c[2]',
    #'Jet_DeepJet_c[3]',
    #'Jet_DeepJet_g[0]',
    #'Jet_DeepJet_g[1]',
    #'Jet_DeepJet_g[2]',
    #'Jet_DeepJet_g[3]',
    #'Jet_DeepJet_lepb[0]',
    #'Jet_DeepJet_lepb[1]',
    #'Jet_DeepJet_lepb[2]',
    #'Jet_DeepJet_lepb[3]',
    #'Jet_DeepJet_uds[0]',
    #'Jet_DeepJet_uds[1]',
    #'Jet_DeepJet_uds[2]',
    #'Jet_DeepJet_uds[3]',

    'Jet_E[0]',
    'Jet_E[1]',
    'Jet_E[2]',
    'Jet_E[3]',
    'Jet_Eta[0]',
    'Jet_Eta[1]',
    'Jet_Eta[2]',
    'Jet_Eta[3]',
    'Jet_M[0]',
    'Jet_M[1]',
    'Jet_M[2]',
    'Jet_M[3]',
    'Jet_Pt[0]',
    'Jet_Pt[1]',
    'Jet_Pt[2]',
    'Jet_Pt[3]',
    'LooseLepton_E[0]',
    'LooseLepton_Eta[0]',
    'LooseLepton_Pt[0]',

    'Evt_CSV_Average',
    'Evt_CSV_Average_Tagged',
    'Evt_CSV_Dev',
    'Evt_CSV_Dev_Tagged',
    'Evt_CSV_Min',
    'Evt_CSV_Min_Tagged',
    'Evt_Deta_JetsAverage',
    'Evt_Deta_TaggedJetsAverage',
    'Evt_Dr_JetsAverage',
    'Evt_Dr_MinDeltaRJets',
    'Evt_Dr_MinDeltaRLeptonJet',
    'Evt_Dr_MinDeltaRLeptonTaggedJet',
    'Evt_Dr_MinDeltaRTaggedJets',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_Eta_JetsAverage',
    'Evt_Eta_TaggedJetsAverage',
    'Evt_HT',
    'Evt_HT_Jets',
    'Evt_JetPtOverJetE',
    'Evt_Jet_MaxDeta_Jets',
    'Evt_M2_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_M3',
    'Evt_MHT',
    'Evt_M_JetsAverage',
    'Evt_M_MedianTaggedJets',
    'Evt_M_MinDeltaRJets',
    'Evt_M_MinDeltaRLeptonJet',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_M_MinDeltaRTaggedJets',
    'Evt_M_TaggedJetsAverage',
    'Evt_M_TaggedJetsClosestTo125',
    'Evt_M_Total',
    'Evt_Pt_MET',
    'Evt_Pt_MinDeltaRJets',
    'Evt_Pt_MinDeltaRTaggedJets',
    'Evt_Pt_PrimaryLepton',
    'Evt_TaggedJet_MaxDeta_Jets',
    'Evt_TaggedJet_MaxDeta_TaggedJets',
    'Evt_blr_ETH',
    'Evt_blr_ETH_transformed',

    'BDT_common5_input_HT_tag',
    'BDT_common5_input_MET',
    'BDT_common5_input_all_sum_pt_with_met',
    'BDT_common5_input_aplanarity',
    'BDT_common5_input_aplanarity_jets',
    'BDT_common5_input_aplanarity_tags',
    'BDT_common5_input_h0',
    'BDT_common5_input_h1',
    'BDT_common5_input_h2',
    'BDT_common5_input_h3',
    'BDT_common5_input_max_dR_bb',
    'BDT_common5_input_max_dR_jj',
    'BDT_common5_input_maxeta_jet_jet',
    'BDT_common5_input_maxeta_jet_tag',
    'BDT_common5_input_maxeta_tag_tag',
    'BDT_common5_input_pt_all_jets_over_E_all_jets',
    'BDT_common5_input_pt_all_jets_over_E_all_jets_tags',
    'BDT_common5_input_sphericity',
    'BDT_common5_input_sphericity_jets',
    'BDT_common5_input_sphericity_tags',
    'BDT_common5_input_tagged_dijet_mass_closest_to_125',
    'BDT_common5_input_transverse_sphericity',
    'BDT_common5_input_transverse_sphericity_jets',
    'BDT_common5_input_transverse_sphericity_tags',

    'N_BTagsL',
    'N_BTagsM',
    'N_BTagsT',
    ]

variables["ge5j_ge3t"] = variables["ge4j_ge3t"] + [
    'CSV[4]',
    #'Jet_DeepJetCSV[4]',
    #'Jet_DeepJet_b[4]',
    #'Jet_DeepJet_bb[4]',
    #'Jet_DeepJet_c[4]',
    #'Jet_DeepJet_g[4]',
    #'Jet_DeepJet_lepb[4]',
    #'Jet_DeepJet_uds[4]',    
    'Jet_E[4]',
    'Jet_Eta[4]',
    'Jet_M[4]',
    #'Jet_Phi[4]',
    'Jet_Pt[4]'
    ]

variables["ge6j_ge3t"] = variables["ge5j_ge3t"] + [
    'CSV[5]',
    #'Jet_DeepJetCSV[5]',
    #'Jet_DeepJet_b[5]',
    #'Jet_DeepJet_bb[5]',
    #'Jet_DeepJet_c[5]',
    #'Jet_DeepJet_g[5]',
    #'Jet_DeepJet_lepb[5]',
    #'Jet_DeepJet_uds[5]',    
    'Jet_E[5]',
    'Jet_Eta[5]',
    'Jet_M[5]',
    #'Jet_Phi[5]',
    'Jet_Pt[5]'
    ]



all_variables = list(set( [v for key in variables for v in variables[key] ] ))

