variables = {}

variables["4j_ge3t"] = [
    "Jet_DeepFlavour_g[3]",
    "Jet_DeepFlavour_b[2]",
    "Jet_DeepFlavour_b[3]",
    "Jet_DeepCSV_bb[3]",
    "BDT_common5_input_closest_tagged_dijet_mass",
    "Evt_HT_Jets",
    "Jet_DeepFlavour_uds[3]",
    "Jet_CSV[2]",
    "Jet_CSV[3]",
    "BDT_common5_input_HT",
    "BDT_common5_input_second_highest_btag",
    "Jet_DeepFlavour_c[2]",
    "CSV[1]",
    "CSV[2]",
    "BDT_common5_input_all_sum_pt_with_met",
    "Jet_DeepCSV_udsg[3]",
    "Evt_HT",
    "BDT_common5_input_HT_tag",
    "BDT_common5_input_third_highest_btag",
    "Jet_DeepCSV_b[3]",
    "Jet_CSV_DNN[2]",
    "Jet_CSV_DNN[3]",
    "BDT_common5_input_avg_dr_tagged_jets",
    "Evt_M_MinDeltaRTaggedJets",
    "Jet_DeepFlavour_bb[3]",
    "Evt_Dr_TaggedJetsAverage",
    "Evt_M2_JetsAverage",
    ]


variables["5j_ge3t"] = [
    "BDT_common5_input_first_jet_pt",
    "Jet_DeepFlavour_b[1]",
    "Jet_DeepFlavour_b[3]",
    "BDT_common5_input_closest_tagged_dijet_mass",
    "Evt_HT_Jets",
    "Jet_CSV[0]",
    "Jet_CSV[1]",
    "BDT_common5_input_HT",
    "CSV[0]",
    "CSV[2]",
    "BDT_common5_input_all_sum_pt_with_met",
    "Evt_HT",
    "BDT_common5_input_third_jet_pt",
    "BDT_common5_input_fourth_jet_pt",
    "BDT_common5_input_HT_tag",
    "BDT_common5_input_third_highest_btag",
    "Jet_DeepCSV_b[0]",
    "Jet_DeepCSV_b[1]",
    "Jet_DeepCSV_b[3]",
    "Jet_CSV_DNN[0]",
    "Evt_M_MedianTaggedJets",
    "Evt_M_MinDeltaRTaggedJets",
    "Jet_Pt[0]",
    "Jet_Pt[2]",
    "Jet_Pt[3]",
    "Evt_M2_JetsAverage",
    ]


variables["ge6j_ge3t"] = [
    "Jet_DeepFlavour_g[0]",
    "BDT_common5_input_closest_tagged_dijet_mass",
    "Evt_HT_Jets",
    "Jet_CSV[0]",
    "BDT_common5_input_HT",
    "Evt_M3",
    "BDT_common5_input_max_dR_bb",
    "BDT_common5_input_Evt_CSV_Average",
    "Jet_DeepFlavour_c[1]",
    "BDT_common5_input_M3",
    "Jet_DeepCSV_udsg[0]",
    "Evt_HT",
    "BDT_common5_input_third_jet_pt",
    "BDT_common5_input_fourth_jet_pt",
    "Evt_CSV_Average_Tagged",
    "Evt_CSV_Average",
    "BDT_common5_input_avg_btag_disc_btags",
    "Jet_DeepCSV_b[0]",
    "Jet_DeepCSV_b[1]",
    "Jet_CSV_DNN[0]",
    "Evt_M_MinDeltaRTaggedJets",
    "Jet_Pt[2]",
    ]



all_variables = set( [v for key in variables for v in variables[key] ] )
