variables = {}

variables["5j_ge3t"] = [
    #"RecoTTZ_TopHad_W_E",
    #"RecoTTZ_TopHad_E",
    #"RecoZ_BJet1_Pt",
    #"RecoHiggs_BJet1_Pt",
    #"RecoHiggs_BJet1_M",
    #"RecoHiggs_Dr",
    #"RecoTTZ_Chi2WHad",
    #"RecoHiggs_Pt",
    #"RecoZ_Dr",
    #"RecoHiggs_Chi2",
    "RecoTTZ_TopLep_W_M",
    "RecoTTZ_Chi2Total",
    "RecoZ_M",
    "RecoHiggs_BJet2_Pt",
    "RecoZ_BJet1_M",
    "RecoZ_Pt",
    "RecoTTZ_TopHad_Pt",
    "RecoHiggs_M",
    "RecoZ_BJet2_Pt",
    "RecoHiggs_M_log",
    "RecoTTZ_TopHad_W_M",
    "RecoZ_M_log",
    "RecoZ_Chi2",
    "RecoTTZ_TopLep_M",
    "RecoTTZ_TopHad_M",
    "RecoTTZ_TopHad_W_Pt",
    "RecoTTZ_Chi2WHad_log",
    "RecoTTZ_Chi2Total_log",
    "RecoZ_Chi2_log",
    "RecoHiggs_Chi2_log",
    ]


variables["ge6j_ge3t"] = [
    #"RecoTTZ_TopHad_BJet_Pt",
    #"RecoTTZ_TopLep_BJet_Pt",
    #"RecoTTZ_Z_BJet1_E",
    #"RecoTTZ_Deta_Z_topHad",
    #"RecoZ_Pt",
    #"RecoTTZ_Dphi_topLep_topHad",
    #"RecoTTZ_TopHad_M",
    #"RecoHiggs_M",
    #"RecoTTZ_Chi2TopHad",
    #"RecoZ_BJet1_M",
    "RecoZ_Chi2",
    "RecoTTZ_Chi2WHad",
    "RecoHiggs_M_log",
    "RecoTTZ_Z_BJet1_Pt",
    "RecoZ_M_log",
    "RecoZ_BJet2_Pt",
    "RecoTTZ_TopLep_W_M",
    "RecoHiggs_Chi2",
    "RecoHiggs_BJet2_Pt",
    "RecoTTZ_Z_Pt",
    "RecoTTZ_Z_M",
    "RecoTTZ_Z_M_log",
    "RecoTTZ_Chi2Total_log",
    "RecoTTZ_Chi2Z",
    "RecoTTZ_TopHad_W_M",
    "RecoZ_M",
    "RecoTTZ_Z_BJet2_Pt",
    "RecoTTZ_Chi2Z_log",
    "RecoZ_Chi2_log",
    "RecoHiggs_Chi2_log",
    ]


variables["4j_ge3t"] = [
    #"RecoTTZ_TopLep_M",
    #"RecoZ_M",
    #"RecoHiggs_Dr",
    #"RecoZ_BJet1_M",
    #"RecoHiggs_M_log",
    #"RecoHiggs_Pt",
    #"RecoTTZ_Chi2TopHad_log",
    #"RecoTTZ_TopHad_E",
    #"RecoTTZ_TopHad_W_Pt",
    #"RecoTTZ_Deta_Lep_topHad",
    "RecoTTZ_Deta_bLep_bHad",
    "RecoHiggs_M",
    "RecoTTZ_TopLep_BJet_Pt",
    "RecoTTZ_Chi2Total",
    "RecoTTZ_Deta_bLep_topHad",
    "RecoZ_Chi2",
    "RecoZ_Pt",
    "RecoZ_M_log",
    "RecoHiggs_BJet2_Pt",
    "RecoZ_BJet2_Pt",
    "RecoTTZ_Chi2TopHad",
    "RecoHiggs_Chi2",
    "RecoTTZ_TopHad_Pt",
    "RecoZ_Chi2_log",
    "RecoHiggs_Chi2_log",
    "RecoTTZ_TopHad_W_M",
    "RecoTTZ_Chi2WHad",
    "RecoTTZ_TopLep_W_M",
    "RecoTTZ_TopHad_M",
    "RecoTTZ_Chi2Total_log",
    ]

variables["ge4j_ge4t"] = [
    "RecoTTZ_Chi2WHad_log",
    "RecoZ_BJet1_Pt",
    "RecoTTZ_Z_Eta",
    "RecoZ_BJet1_M",
    "RecoHiggs_Pt",
    "RecoTTZ_TopHad_M",
    "RecoTTZ_Dphi_Z_topLep",
    "RecoTTZ_Deta_Z_topHad",
    "RecoHiggs_M_log",
    "RecoHiggs_BJet2_Pt",
    "RecoTTZ_Dphi_Z_bLep",
    "RecoZ_BJet2_Pt",
    "RecoTTZ_Dphi_Z_Lep",
    "RecoZ_Chi2",
    "RecoZ_M",
    "RecoTTZ_Chi2Total_log",
    "RecoHiggs_Chi2_log",
    "RecoTTZ_TopLep_W_M",
    "RecoHiggs_Chi2",
    "RecoZ_Chi2_log",
    ]


variables["4j_ge3t"] = [
    "RecoTTZ_Deta_bLep_bHad",
    "RecoHiggs_M",
    "RecoTTZ_TopLep_BJet_Pt",
    "RecoTTZ_Chi2Total",
    "RecoTTZ_Deta_bLep_topHad",
    "RecoZ_Chi2",
    "RecoZ_Pt",
    "RecoZ_M_log",
    "RecoHiggs_BJet2_Pt",
    "RecoZ_BJet2_Pt",
    "RecoTTZ_Chi2TopHad",
    "RecoHiggs_Chi2",
    "RecoTTZ_TopHad_Pt",
    "RecoZ_Chi2_log",
    "RecoHiggs_Chi2_log",
    "RecoTTZ_TopHad_W_M",
    "RecoTTZ_Chi2WHad",
    "RecoTTZ_TopLep_W_M",
    "RecoTTZ_TopHad_M",
    "RecoTTZ_Chi2Total_log",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
