variables = {}

variables["ge4j_3t"] = [
    "RecoHiggs_BJet1_Pt",
    "RecoTTZ_TopLep_BJet_Eta",
    "RecoTTZ_TopHad_BJet_Eta",
    "RecoZ_Chi2",
    "RecoTTZ_TopHad_Pt",
    "RecoZ_BJet1_M",
    "RecoTTZ_TopLep_Eta",
    "RecoTTZ_Chi2Total_log",
    "RecoZ_M_log",
    "RecoHiggs_BJet1_M",
    "RecoHiggs_Chi2",
    "RecoHiggs_Dr",
    "RecoTTZ_TopLep_W_Eta",
    "RecoTTZ_Dphi_topLep_topHad",
    "RecoZ_Eta",
    "RecoZ_BJet1_Eta",
    "RecoHiggs_M",
    "RecoHiggs_M_log",
    "RecoHiggs_Chi2_log",
    "RecoZ_Chi2_log",
    ]


variables["5j_ge3t"] = [
    "RecoZ_cosdTheta",
    "RecoHiggs_Dr",
    "RecoHiggs_BJet2_M",
    "RecoTTZ_Chi2TopLep_log",
    "RecoHiggs_Pt",
    "RecoZ_BJet2_Pt",
    "RecoTTZ_Deta_Lep_topHad",
    "RecoHiggs_BJet1_M",
    "RecoHiggs_BJet1_Pt",
    "RecoZ_M_log",
    "RecoZ_Chi2",
    "RecoZ_Pt",
    "RecoTTZ_Chi2Total_log",
    "RecoZ_M",
    "RecoZ_BJet1_M",
    "RecoHiggs_Chi2",
    "RecoHiggs_M",
    "RecoHiggs_M_log",
    "RecoHiggs_Chi2_log",
    "RecoZ_Chi2_log",
    ]


variables["ge6j_ge3t"] = [
    "RecoTTZ_Deta_Lep_topHad",
    "RecoZ_M",
    "RecoZ_M_log",
    "RecoZ_Chi2",
    "RecoHiggs_BJet1_M",
    "RecoTTZ_Z_BJet1_Pt",
    "RecoHiggs_BJet2_Pt",
    "RecoTTZ_Z_BJet2_Pt",
    "RecoZ_BJet1_M",
    "RecoHiggs_M",
    "RecoTTZ_Deta_Z_Lep",
    "RecoHiggs_M_log",
    "RecoHiggs_Chi2",
    "RecoTTZ_Z_Pt",
    "RecoTTZ_Z_M",
    "RecoTTZ_Z_M_log",
    "RecoZ_Chi2_log",
    "RecoTTZ_Chi2Z",
    "RecoTTZ_Chi2Z_log",
    "RecoHiggs_Chi2_log",
    ]


variables["ge4j_ge4t"] = [
    "RecoHiggs_BJet2_Pt",
    "RecoZ_BJet1_Eta",
    "RecoZ_BJet1_E",
    "RecoHiggs_BJet1_Eta",
    "RecoZ_BJet1_Pt",
    "RecoHiggs_BJet2_M",
    "RecoTTZ_Chi2Total_log",
    "RecoZ_Eta",
    "RecoZ_BJet1_M",
    "RecoHiggs_Pt",
    "RecoZ_BJet2_Pt",
    "RecoZ_M",
    "RecoZ_Pt",
    "RecoZ_M_log",
    "RecoHiggs_M",
    "RecoHiggs_M_log",
    "RecoHiggs_Chi2_log",
    "RecoZ_Chi2_log",
    "RecoZ_Chi2",
    "RecoHiggs_Chi2",
    ]


variables["4j_ge3t"] = [
    "RecoZ_M",
    "RecoZ_M_log",
    "RecoZ_Chi2",
    "RecoHiggs_Dphi",
    "RecoTTZ_Dphi_bLep_topHad",
    "RecoZ_Eta",
    "RecoZ_BJet2_Pt",
    "RecoHiggs_Dr",
    "RecoTTZ_Chi2WHad_log",
    "RecoHiggs_BJet1_M",
    "RecoTTZ_Chi2Total_log",
    "RecoHiggs_Chi2",
    "RecoTTZ_Deta_Lep_topHad",
    "RecoTTZ_TopHad_Pt",
    "RecoTTZ_Chi2TopHad_log",
    "RecoTTZ_Chi2Total",
    "RecoHiggs_BJet1_Pt",
    "RecoZ_BJet1_M",
    "RecoHiggs_Chi2_log",
    "RecoZ_Chi2_log",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
