variables = {}

variables["6j_3t"] = [
    "Reco_JABDT_ttH_Jet_CSV_hdau1",
    "Reco_ttH_hdau_m1",
    "Reco_ttH_bestJABDToutput",
    "Evt_M2_closestTo91TaggedJets",
    "TaggedJet_M[0]",
    "Evt_Dr_TaggedJetsAverage",
    "Reco_ttH_hdau_pt2",
    "Evt_M2_TaggedJetsAverage",
    "Evt_HT_tags",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M2_minDrTaggedJets",
    "Reco_ttH_hdau_pt1",
    "Evt_Pt_minDrTaggedJets",
    "TaggedJet_Pt[0]",
    "Reco_ttH_h_m",
    "Jet_Pt[0]",
    "Reco_ttH_h_dr",
    "Reco_JABDT_ttH_log_h_m",
    "Reco_JABDT_ttH_log_h_pt",
    "Reco_ttH_h_pt",
    ]


variables["5j_3t"] = [
    "Reco_JABDT_ttbar_Jet_CSV_whaddau1",
    "TaggedJet_Pt[2]",
    "Evt_M3",
    "Evt_M2_closestTo125TaggedJets",
    "TaggedJet_Pt[1]",
    "TaggedJet_M[0]",
    "Evt_M2_minDrJets",
    "Evt_M_TaggedJetsAverage",
    "Evt_HT_tags",
    "Evt_M2_closestTo91TaggedJets",
    "Evt_Pt_TaggedJetsAverage",
    "Evt_M2_TaggedJetsAverage",
    "Evt_Dr_TaggedJetsAverage",
    "Evt_Pt_minDrJets",
    "Jet_Pt[0]",
    "Evt_HT",
    "TaggedJet_Pt[0]",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M2_minDrTaggedJets",
    "Evt_Pt_minDrTaggedJets",
    ]


variables["ge7j_3t"] = [
    "Reco_JABDT_ttH_Jet_CSV_hdau2",
    "Reco_ttH_bestJABDToutput",
    "TaggedJet_Pt[2]",
    "Evt_M2_closestTo125TaggedJets",
    "Reco_ttH_hdau_m1",
    "TaggedJet_M[0]",
    "Evt_Dr_TaggedJetsAverage",
    "TaggedJet_Pt[1]",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M2_minDrTaggedJets",
    "Reco_ttH_hdau_pt2",
    "Jet_Pt[0]",
    "Evt_Pt_minDrTaggedJets",
    "Reco_ttH_h_m",
    "Reco_ttH_h_dr",
    "TaggedJet_Pt[0]",
    "Reco_JABDT_ttH_log_h_m",
    "Reco_ttH_hdau_pt1",
    "Reco_JABDT_ttH_log_h_pt",
    "Reco_ttH_h_pt",
    ]


variables["ge7j_ge4t"] = [
    "Reco_JABDT_ttH_Jet_CSV_hdau1",
    "Reco_JABDT_ttH_Jet_CSV_hdau2",
    "Reco_ttH_hdau_m2",
    "Reco_ttH_hdau_m1",
    "Evt_Deta_TaggedJetsAverage",
    "TaggedJet_M[0]",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M2_TaggedJetsAverage",
    "Evt_M2_minDrTaggedJets",
    "Evt_Dr_TaggedJetsAverage",
    "Reco_ttH_hdau_pt2",
    "Evt_Pt_minDrTaggedJets",
    "TaggedJet_Pt[0]",
    "Reco_ttH_hdau_pt1",
    "Reco_ttH_h_m",
    "Reco_JABDT_ttH_log_h_m",
    "Evt_Pt_TaggedJetsAverage",
    "Reco_ttH_h_dr",
    "Reco_JABDT_ttH_log_h_pt",
    "Reco_ttH_h_pt",
    ]


variables["4j_ge4t"] = [
    "Reco_ttbar_btoplep_pt",
    "Reco_ttbar_whaddau_m1",
    "TaggedJet_Pt[1]",
    "Reco_ttH_h_m",
    "Evt_HT_wo_MET",
    "Evt_Dr_minDrJets",
    "Reco_ttH_h_dr",
    "Evt_Dr_minDrTaggedJets",
    "Evt_HT_jets",
    "Evt_HT_tags",
    "Evt_Pt_TaggedJetsAverage",
    "TaggedJet_M[0]",
    "TaggedJet_Pt[0]",
    "Evt_Pt_JetsAverage",
    "Evt_M2_minDrJets",
    "Evt_M2_minDrTaggedJets",
    "Evt_Pt_minDrTaggedJets",
    "Evt_Pt_minDrJets",
    "Jet_Pt[0]",
    "Evt_HT",
    ]


variables["6j_ge4t"] = [
    "Reco_JABDT_ttH_Jet_CSV_hdau2",
    "Reco_ttH_hdau_m2",
    "Reco_ttH_hdau_m1",
    "Reco_ttH_bestJABDToutput",
    "TaggedJet_M[0]",
    "Evt_M2_minDrTaggedJets",
    "Evt_Dr_minDrTaggedJets",
    "Evt_Dr_TaggedJetsAverage",
    "Reco_ttH_hdau_pt2",
    "Jet_Pt[0]",
    "Evt_Pt_TaggedJetsAverage",
    "TaggedJet_Pt[0]",
    "Evt_M2_TaggedJetsAverage",
    "Evt_Pt_minDrTaggedJets",
    "Reco_ttH_h_m",
    "Reco_ttH_hdau_pt1",
    "Reco_ttH_h_dr",
    "Reco_JABDT_ttH_log_h_m",
    "Reco_JABDT_ttH_log_h_pt",
    "Reco_ttH_h_pt",
    ]


variables["4j_3t"] = [
    "Evt_Dr_JetsAverage",
    "TaggedJet_Pt[2]",
    "Jet_M[0]",
    "Evt_M2_closestTo91TaggedJets",
    "Evt_M3",
    "Jet_Pt[1]",
    "TaggedJet_Pt[1]",
    "Evt_Dr_minDrJets",
    "Evt_M_TaggedJetsAverage",
    "Evt_Dr_TaggedJetsAverage",
    "TaggedJet_M[0]",
    "Evt_Pt_minDrJets",
    "Evt_HT_tags",
    "Jet_Pt[0]",
    "Evt_M2_TaggedJetsAverage",
    "Evt_Dr_minDrTaggedJets",
    "Evt_HT",
    "TaggedJet_Pt[0]",
    "Evt_M2_minDrTaggedJets",
    "Evt_Pt_minDrTaggedJets",
    ]


variables["5j_ge4t"] = [
    "Evt_Dr_maxDrTaggedJets",
    "Jet_M[0]",
    "Reco_ttbar_tophad_pt",
    "Reco_ttH_h_pt",
    "Evt_M3",
    "Reco_ttH_bestJABDToutput",
    "TaggedJet_Pt[1]",
    "Jet_Pt[1]",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_HT_tags",
    "Reco_ttH_h_dr",
    "TaggedJet_M[0]",
    "Evt_M2_TaggedJetsAverage",
    "Jet_Pt[0]",
    "Evt_Dr_TaggedJetsAverage",
    "TaggedJet_Pt[0]",
    "Evt_Dr_minDrTaggedJets",
    "Evt_Pt_TaggedJetsAverage",
    "Evt_M2_minDrTaggedJets",
    "Evt_Pt_minDrTaggedJets",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
