variables = {}
variables["ge4j_ge3t"] = [
    #"Evt_MET_Phi",
    "Evt_MET_Pt",
    "Evt_HT",
    "N_BTagsM",
    "N_Jets",
    "RecoTT_TopHad_B_Pt",
    #"RecoTT_TopHad_B_Eta",
    #"RecoTT_TopHad_B_Phi",
    #"RecoTT_TopHad_B_E",
    "RecoTT_TopHad_B_CSV",
    "RecoTT_TopLep_B_Pt",
    #"RecoTT_TopLep_B_Eta",
    #"RecoTT_TopLep_B_Phi",
    #"RecoTT_TopLep_B_E",
    "RecoTT_TopLep_B_CSV",
    "RecoTT_TopHad_Q1_Pt",
    #"RecoTT_TopHad_Q1_Eta",
    #"RecoTT_TopHad_Q1_Phi",
    #"RecoTT_TopHad_Q1_E",
    "RecoTT_TopHad_Q1_CSV",
    "RecoTT_TopHad_Q2_Pt",
    #"RecoTT_TopHad_Q2_Eta",
    #"RecoTT_TopHad_Q2_Phi",
    #"RecoTT_TopHad_Q2_E",
    "RecoTT_TopHad_Q2_CSV",
    "RecoTT_TopHad_Pt",
    #"RecoTT_TopHad_Eta",
    #"RecoTT_TopHad_Phi",
    "RecoTT_TopHad_M",
    "RecoTT_TopHad_logM",
    "RecoTT_TopLep_Pt",
    #"RecoTT_TopLep_Eta",
    #"RecoTT_TopLep_Phi",
    "RecoTT_TopLep_M",
    "RecoTT_TopLep_logM",
    "RecoTT_WHad_Pt",
    #"RecoTT_WHad_Eta",
    #"RecoTT_WHad_Phi",
    "RecoTT_WHad_M",
    "RecoTT_WHad_logM",
    "RecoTT_WLep_Pt",
    #"RecoTT_WLep_Eta",
    #"RecoTT_WLep_Phi",
    "RecoTT_WLep_M",
    "RecoTT_WLep_logM",
    #"RecoTT_ttbar_Phi",
    "RecoTT_ttbar_energy_fraction",
    ]



all_variables = list(set( [v for key in variables for v in variables[key] ] ))
