variables = {}

variables["ge4j_ge3t"] = [
    # "Reco_tHW_h_pt",
    # "Reco_tHW_whad_pt",
    # "Reco_tHW_whad_m",

    "Reco_JABDT_ttbar_Jet_CSV_btoplep",
    "Reco_ttbar_btoplep_m",
    "Reco_ttbar_toplep_m",
    "Reco_ttbar_whaddau_m1",
    "Reco_ttbar_tophad_m",
    "Reco_ttbar_whad_m",
    "Reco_ttH_toplep_m",

    "Evt_CSV_min_tagged",
    "Evt_Dr_minDrTaggedJets",
    "Evt_HT_wo_MET",
    "Evt_HT",
    "Reco_LeptonicW_M",
    "Evt_HT_jets",
    "Evt_CSV_avg",
    "Evt_CSV_dev",
    "Evt_CSV_dev_tagged",
    "Evt_CSV_avg_tagged",
    "Evt_M_TaggedJetsAverage",
    "Evt_M2_minDrTaggedJets",
    "Evt_M2_TaggedJetsAverage",
    "Evt_Deta_JetsAverage",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_M_JetsAverage",
    "Evt_Pt_minDrTaggedJets",
    "Jet_Pt[0]",
    "CSV[2]",
    "CSV[3]",
    ]


variables["ge4j_ge4t"] = [

    # "Reco_tHW_wtop_pt",
    # "Reco_tHq_hdau_eta2",
    # "Reco_tHq_top_phi",
    # "Reco_tHW_whaddau_pt1",
    # "Reco_tHW_wb_pt",
    # "Reco_tHW_btop_m",
    # "Reco_tHW_bestJABDToutput",
    # "Reco_tHq_btop_lep_dr",
    # "Reco_tHW_whad_phi",
    # "Reco_JABDT_tHW_abs_btop_eta",
    # "Reco_JABDT_tHq_abs_btop_eta",
    # "Reco_JABDT_tHq_costheta_btop_lep",
    # "Reco_JABDT_tHW_log_top_m",


    "Reco_ttbar_btophad_eta",
    "Reco_ttH_tophad_m", #
    "Reco_ttH_h_phi",
    "Reco_ttH_h_eta",
    "Reco_ttH_tophad_pt",
    "Reco_ttH_whad_dr",
    "Reco_ttH_whaddau_m2",
    "Reco_JABDT_ttH_tophad_pt__P__toplep_pt__P__h_pt__DIV__Evt_HT__P__Evt_Pt_MET__P__Lep_Pt",
    "Reco_JABDT_ttbar_log_toplep_pt",
    "Reco_JABDT_ttbar_Jet_CSV_whaddau1",
    "Evt_HT",
    "Evt_M_JetsAverage",
    "Evt_M_TaggedJetsAverage",
    "Evt_CSV_avg_tagged",
    "N_BTagsT",
    "CSV[2]",
    "CSV[3]",
    #additional
    "Jet_CSV[3]",
    "Evt_M_minDrLepTag",
    "N_BTagsT",
    "Jet_Pt[0]",
    "Evt_CSV_dev",
    "Evt_M2_closestTo125TaggedJets",
    "Evt_sphericity_jets",
    "Evt_Pt_minDrTaggedJets",
    "Evt_transverse_sphericity_jets",
    "Evt_CSV_min_tagged",
    "Evt_CSV_avg_tagged",
    "Evt_CSV_avg",
    "Evt_CSV_min",
    "Evt_M_JetsAverage",
    "Evt_M2_TaggedJetsAverage",
    ]


variables["ge4j_3t"] = [
    "Reco_ttbar_tophad_m",

    "Evt_CSV_avg",
    "Evt_Deta_JetsAverage",
    "Evt_M2_TaggedJetsAverage",
    "Evt_HT_wo_MET",
    "Evt_HT_jets",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_CSV_avg_tagged",
    "Evt_CSV_dev_tagged",
    "Evt_CSV_dev",
    "Evt_M_JetsAverage",
    "Evt_CSV_min_tagged",
    "CSV[2]",
    "Evt_Pt_minDrTaggedJets",
    "Evt_M_TaggedJetsAverage",
    #additional
    "Jet_CSV[3]",
    "Evt_M_minDrLepTag",
    "N_BTagsT",
    "Jet_Pt[0]",
    "Evt_M2_closestTo125TaggedJets",
    "Evt_sphericity_jets",
    "Evt_transverse_sphericity_jets",
    "Evt_CSV_min",

    # "Reco_tHq_h_dr",
    # "Reco_tHW_whad_m",
    # "Reco_JABDT_tHq_costheta_btop_lep",
    # "Reco_tHq_btop_w_dr",
    # "Reco_JABDT_tHq_log_top_m",
    # "Reco_JABDT_tHq_Jet_CSV_hdau2",
    # #"Reco_tHq_bestJABDToutput",
    # "Reco_JABDT_tHq_abs_ljet_eta__M__btop_eta",
    # "Reco_JABDT_tHq_log_ljet_pt",
    # "Reco_tHq_top_h_dr",
    # "Reco_tHq_costhetastar",
    # "Reco_JABDT_tHq_log_min_hdau1_pt_hdau2_pt",
    # "Reco_JABDT_tHq_log_h_m",
    # "Reco_JABDT_tHq_Jet_CSV_hdau1",
    # "Reco_JABDT_tHq_Jet_CSV_btop",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
