variables = {}
variables["4j_ge3t"] = [
    "MVA_cos_theta_blep_bhad",
    "Evt_Jet_MaxDeta_Jets",
    "Evt_Dr_MinDeltaRLeptonTaggedJet",
    "MVA_Evt_Deta_JetsAverage",
    "MVA_h1",
    "Jet_Pt[1]",
    "MVA_MET",
    "Jet_Pt[2]",
    "MVA_aplanarity",
    "Jet_M[3]",
    "Evt_Pt_MET",
    "Evt_M_TaggedJetsAverage",
    "MVA_max_dR_jj",
    "Jet_Pt[3]",
    "Jet_Pt[0]",
    "N_LooseJets",
    "Evt_Dr_MinDeltaRJets",
    "LooseLepton_Pt[0]",
    "MVA_closest_tagged_dijet_mass",
    "Evt_Dr_MinDeltaRTaggedJets",
    "Jet_M[0]",
    "Evt_M_MinDeltaRTaggedJets",
    "Evt_Pt_MinDeltaRJets",
    "Evt_Dr_JetsAverage",
    "Evt_M_MinDeltaRJets",
    "MVA_M3",
    "MVA_MHT",
    "MVA_tagged_dijet_mass_closest_to_125",
    "Evt_Pt_MinDeltaRTaggedJets",
    ]

variables["ge4j_3t"] = [

    "Evt_M_MinDeltaRLeptonTaggedJet",
    "CSV[3]",
    "Evt_M2_JetsAverage",
    "Evt_Pt_MET",
    "MVA_delta_eta_l_bhad",
    "Jet_DeepJetCSV[0]",
    "MVA_HT_tag",
    "Jet_Pt[3]",
    "MVA_M3",
    "MVA_aplanarity",
    "Evt_Dr_MinDeltaRJets",
    "MVA_h1",
    "Evt_Dr_JetsAverage",
    "Evt_M_MinDeltaRJets",
    "Evt_Dr_MinDeltaRLeptonTaggedJet",
    "Evt_M_TaggedJetsAverage",
    "N_LooseJets",
    "Evt_Pt_MinDeltaRJets",
    "LooseLepton_Pt[0]",
    "Evt_M_JetsAverage",
    "Jet_M[0]",
    "MVA_Evt_Deta_JetsAverage",
    "MVA_Evt_Deta_TaggedJetsAverage",
    "MVA_MHT",
    "MVA_closest_tagged_dijet_mass",
    "Evt_M_MinDeltaRTaggedJets",
    "Jet_Pt[0]",
    "MVA_tagged_dijet_mass_closest_to_125",
    "Evt_Dr_MinDeltaRTaggedJets",
    "Evt_Pt_MinDeltaRTaggedJets"


    ]


variables["ge4j_ge4t"] = [

    "Evt_M_MinDeltaRJets",
    "Evt_M2_JetsAverage",
    "CSV[1]",
    "MVA_h1",
    "Jet_E[1]",
    "LooseLepton_E[0]",
    "Jet_DeepJetCSV[1]",
    "Jet_Pt[3]",
    "MVA_MHT",
    "Jet_Pt[2]",
    "MVA_aplanarity",
    "MVA_cos_theta_l_bhad",
    "Jet_DeepJetCSV[0]",
    "Evt_M_TaggedJetsAverage",
    "Evt_Dr_JetsAverage",
    "Jet_M[0]",
    "Evt_Dr_MinDeltaRLeptonTaggedJet",
    "Evt_Pt_MinDeltaRJets",
    "MVA_HT_tag",
    "N_BTagsL",
    "CSV[2]",
    "MVA_M3",
    "MVA_Evt_Deta_JetsAverage",
    "Evt_M_MedianTaggedJets",
    "Evt_Dr_MinDeltaRTaggedJets",
    "Jet_Pt[0]",
    "MVA_tagged_dijet_mass_closest_to_125",
    "Evt_Pt_MinDeltaRTaggedJets",
    "Evt_M_MinDeltaRTaggedJets",
    "MVA_closest_tagged_dijet_mass",

    ]



variables["ge4j_ge3t"] = [

    "MVA_delta_eta_blep_bhad",
    "Evt_Dr_MinDeltaRJets",
    "Evt_M_MinDeltaRJets",
    "MVA_cos_theta_blep_bhad",
    "Evt_M2_JetsAverage",
    "CSV[3]",
    "MVA_h1",
    "Jet_Pt[3]",
    "MVA_invariant_mass_of_everything",
    "MVA_aplanarity",
    "Evt_Dr_JetsAverage",
    "MVA_HT_tag",
    "Jet_DeepJetCSV[0]",
    "Evt_M_JetsAverage",
    "N_LooseJets",
    "MVA_M3",
    "LooseLepton_Pt[0]",
    "Evt_Pt_MinDeltaRJets",
    "Evt_M_TaggedJetsAverage",
    "MVA_Evt_Deta_TaggedJetsAverage",
    "MVA_tagged_dijet_mass_closest_to_125",
    "MVA_MHT",
    "Evt_Dr_MinDeltaRLeptonTaggedJet",
    "Jet_Pt[0]",
    "MVA_Evt_Deta_JetsAverage",
    "Jet_M[0]",
    "Evt_Dr_MinDeltaRTaggedJets",
    "MVA_closest_tagged_dijet_mass",
    "Evt_M_MinDeltaRTaggedJets",
    "Evt_Pt_MinDeltaRTaggedJets",

    ]


variables["le5j_ge3t"] = [

    "Jet_Pt[1]",
    "Evt_M2_JetsAverage",
    "MVA_cos_theta_blep_bhad",
    "MVA_HT_tag",
    "MVA_aplanarity",
    "N_LooseJets",
    "Jet_DeepJetCSV[0]",
    "Jet_Pt[3]",
    "LooseLepton_Pt[0]",
    "Evt_Dr_MinDeltaRJets",
    "Evt_Dr_MinDeltaRLeptonTaggedJet",
    "MVA_cos_theta_l_bhad",
    "Evt_M_JetsAverage",
    "MVA_h1",
    "CSV[3]",
    "Evt_Dr_JetsAverage",
    "MVA_Evt_Deta_TaggedJetsAverage",
    "Jet_Pt[0]",
    "Evt_M_MinDeltaRJets",
    "Evt_M_TaggedJetsAverage",
    "Evt_Pt_MinDeltaRJets",
    "MVA_M3",
    "MVA_Evt_Deta_JetsAverage",
    "MVA_MHT",
    "Evt_Dr_MinDeltaRTaggedJets",
    "Jet_M[0]",
    "Evt_M_MinDeltaRTaggedJets",
    "MVA_closest_tagged_dijet_mass",
    "MVA_tagged_dijet_mass_closest_to_125",
    "Evt_Pt_MinDeltaRTaggedJets",


    ]

variables["5j_ge3t"] = [

    "Evt_M_MedianTaggedJets",
    "N_LooseJets",
    "MVA_aplanarity",
    "Jet_Pt[4]",
    "Evt_Dr_JetsAverage",
    "MVA_MET",
    "MVA_Evt_M2_TaggedJetsAverage",
    "MVA_delta_eta_blep_bhad",
    "Evt_M_MinDeltaRLeptonJet",
    "MVA_cos_theta_l_bhad",
    "MVA_M3",
    "LooseLepton_Pt[0]",
    "Evt_Dr_MinDeltaRLeptonTaggedJet",
    "Evt_Pt_MET",
    "Evt_Dr_MinDeltaRJets",
    "MVA_Evt_Deta_TaggedJetsAverage",
    "MVA_Evt_Deta_JetsAverage",
    "Evt_M_TaggedJetsAverage",
    "Jet_Pt[0]",
    "Jet_Pt[3]",
    "CSV[3]",
    "Jet_M[0]",
    "MVA_MHT",
    "Evt_M_MinDeltaRJets",
    "Evt_M_MinDeltaRTaggedJets",
    "Evt_Pt_MinDeltaRJets",
    "MVA_closest_tagged_dijet_mass",
    "Evt_Dr_MinDeltaRTaggedJets",
    "MVA_tagged_dijet_mass_closest_to_125",
    "Evt_Pt_MinDeltaRTaggedJets",


    ]

variables["ge6j_ge3t"] = [
    "MVA_cos_theta_blep_bhad",
    "CSV[3]",
    "MVA_aplanarity",
    "MVA_delta_eta_l_bhad",
    "MVA_best_higgs_mass",
    "Evt_M_JetsAverage",
    "MVA_invariant_mass_of_everything",
    "MVA_cos_theta_l_bhad",
    "LooseLepton_Pt[0]",
    "N_LooseJets",
    "Evt_Pt_MinDeltaRJets",
    "MVA_M3",
    "Jet_Pt[5]",
    "Evt_M_MinDeltaRJets",
    "MVA_Evt_Deta_TaggedJetsAverage",
    "Jet_DeepJetCSV[0]",
    "MVA_MHT",
    "Evt_M_MinDeltaRLeptonTaggedJet",
    "MVA_HT_tag",
    "MVA_Evt_Deta_JetsAverage",
    "Jet_M[0]",
    "Jet_Pt[0]",
    "MVA_Mlb",
    "Evt_Dr_MinDeltaRLeptonTaggedJet",
    "Evt_M_TaggedJetsAverage",
    "MVA_tagged_dijet_mass_closest_to_125",
    "Evt_Dr_MinDeltaRTaggedJets",
    "Evt_M_MinDeltaRTaggedJets",
    "MVA_closest_tagged_dijet_mass",
    "Evt_Pt_MinDeltaRTaggedJets",

    ]


all_variables = list(set( [v for key in variables for v in variables[key] ] ))
