variables = {}

variables["le5j_ge3t"] = [
    "Jet_Pt[3]",
    "Evt_Pt_minDrJets",
    "Jet_Pt[0]",
    "Evt_CSV_dev_tagged",
    "Evt_Deta_TaggedJetsAverage",
    "Jet_M[0]",
    "Evt_MHT",
    "Evt_M2_closestTo91TaggedJets",
    "Evt_MTW",
    "Evt_M2_closestTo125TaggedJets",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M2_minDrTaggedJets",
    "Jet_DeepJetCSV[0]",
    "Evt_CSV_avg",
    "RecoTTZ_TopLep_M",
    "RecoTTZ_TopHad_M",
    "CSV[2]",
    "CSV[3]",
    "Evt_Pt_minDrTaggedJets",
    "Evt_M_TaggedJetsAverage",
    ]


variables["ge4j_ge3t"] = [
    "Evt_CSV_dev_tagged",
    "Evt_M2_closestTo125TaggedJets",
    "Evt_MTW",
    "Evt_Dr_minDrLepTag",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_M_minDrLepTag",
    "Evt_M2_closestTo91TaggedJets",
    "Jet_M[0]",
    "Jet_DeepJetCSV[0]",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M_JetsAverage",
    "Jet_Pt[0]",
    "RecoTTZ_TopLep_M",
    "RecoTTZ_TopHad_M",
    "Evt_CSV_avg",
    "Evt_M2_minDrTaggedJets",
    "CSV[3]",
    "Evt_M_TaggedJetsAverage",
    "CSV[2]",
    "Evt_Pt_minDrTaggedJets",
    ]


variables["ge4j_ge4t"] = [
    "Jet_M[0]",
    "Evt_M_TaggedJetsAverage",
    "Evt_Dr_TaggedJetsAverage",
    "Evt_M_minDrLepTag",
    "Evt_CSV_min_tagged",
    "Evt_Deta_JetsAverage",
    "Evt_CSV_avg",
    "Evt_M2_closestTo125TaggedJets",
    "Evt_M2_minDrTaggedJets",
    "Evt_h0",
    "Evt_CSV_dev",
    "CSV[3]",
    "Jet_Pt[0]",
    "N_BTagsM",
    "Evt_Deta_TaggedJetsAverage",
    "N_BTagsL",
    "Evt_M2_closestTo91TaggedJets",
    "Evt_CSV_avg_tagged",
    "Evt_Pt_minDrTaggedJets",
    "CSV[2]",
    ]


variables["ge4j_3t"] = [
    "CSV[2]",
    "Evt_CSV_min_tagged",
    "Evt_M2_closestTo125TaggedJets",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M2_closestTo91TaggedJets",
    "Evt_CSV_dev_tagged",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_M_minDrLepTag",
    "Evt_Dr_minDrLepTag",
    "Evt_MTW",
    "Evt_M2_minDrTaggedJets",
    "Jet_M[0]",
    "Evt_M_JetsAverage",
    "RecoTTZ_TopLep_M",
    "Jet_Pt[0]",
    "Evt_CSV_avg",
    "Jet_DeepJetCSV[0]",
    "RecoTTZ_TopHad_M",
    "Evt_Pt_minDrTaggedJets",
    "Evt_M_TaggedJetsAverage",
    ]


variables["ge6j_ge3t"] = [
    "Evt_Deta_TaggedJetsAverage",
    "RecoTTZ_TopLep_M",
    "RecoTTZ_TopHad_M",
    "RecoTTZ_Z_BJet2_Pt",
    "Evt_M2_closestTo125TaggedJets",
    "Jet_M[0]",
    "Evt_M_JetsAverage",
    "Evt_M2_minDrTaggedJets",
    "RecoTTZ_Z_M",
    "Evt_CSV_dev_tagged",
    "RecoTTZ_Chi2Z",
    "Evt_MTW",
    "Evt_Dr_minDrLepTag",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M_minDrLepTag",
    "Evt_CSV_dev",
    "Evt_M_TaggedJetsAverage",
    "Evt_Pt_minDrTaggedJets",
    "CSV[2]",
    "CSV[3]",
    ]


variables["4j_ge3t"] = [
    "RecoTTZ_Chi2TopHad",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M2_minDrTaggedJets",
    "Jet_M[0]",
    "Evt_M2_closestTo125TaggedJets",
    "RecoTTZ_Chi2WHad",
    "Evt_M2_minDrJets",
    "Evt_CSV_dev_tagged",
    "Evt_Pt_minDrJets",
    "Jet_DeepJetCSV[0]",
    "Evt_M2_closestTo91TaggedJets",
    "Evt_CSV_dev",
    "RecoTTZ_TopHad_Pt",
    "Evt_MTW",
    "Evt_MHT",
    "RecoTTZ_TopLep_M",
    "Evt_Pt_minDrTaggedJets",
    "CSV[2]",
    "Evt_M_TaggedJetsAverage",
    "RecoTTZ_TopHad_M",
    ]


variables["5j_ge3t"] = [
    "Evt_Deta_TaggedJetsAverage",
    "Evt_Dr_minDrLepTag",
    "Jet_DeepJetCSV[0]",
    "Jet_M[0]",
    "Evt_M_minDrLepTag",
    "Evt_MHT",
    "Evt_CSV_avg",
    "Evt_CSV_dev_tagged",
    "Evt_MTW",
    "Evt_M2_closestTo125TaggedJets",
    "Evt_CSV_dev",
    "Evt_M2_closestTo91TaggedJets",
    "RecoTTZ_TopLep_M",
    "Evt_Dr_minDrTaggedJets",
    "Evt_M2_minDrTaggedJets",
    "RecoTTZ_TopHad_M",
    "CSV[2]",
    "CSV[3]",
    "Evt_M_TaggedJetsAverage",
    "Evt_Pt_minDrTaggedJets",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
