variables = {}

variables["3j_2t"] = [
    'btagDiscriminatorAverage_untagged',
    'N_btags_Loose',
    'ptSum_jets_leptons',
    'pT_jet_tag_min_deltaR',
    'pT_jet_jet_min_deltaR',
    'maxDeltaEta_jet_jet',
    'jet3_btag',
    'HT_jets',
    'pT_tag_tag_min_deltaR',
    'jet1_pt',
    'avgDeltaR_jet_tag',
    'avgDeltaR_jet_jet',
    'R1_jet',
    'jet3_pt',
    'R1_tag',
    'H1_jet',
    'HT_tags',
    'jet2_pt',
    'H1_tag',
    'lepton1_pt',
    'maxDeltaEta_tag_tag',
    'avgDeltaR_tag_tag',
    'minDeltaR_tag_tag',
    'dilepton_pt',
    'mass_jet_tag_min_deltaR',
    'mass_jet_jet_min_deltaR',
    'bjet1_pt',
    'minDeltaR_jet_jet',
    'bjet2_pt',
    'met_pt',
    'twist_jet_tag_max_mass',
    'twist_jet_jet_max_mass',
    'multiplicity_higgsLikeDijet15',
    'jet2_btag',
    'lepton2_pt',
    'dilepton_M',
    'mass_higgsLikeDijet',
    'mass_tag_tag_max_mass',
    'mass_tag_tag_min_deltaR',
    'mass_jet_tag_tag_max_pT'
    ]

variables["3j_3t"] = [
    'btagDiscriminatorAverage_tagged',
    'bjet3_btag',
    'maxDeltaEta_tag_tag',
    'maxDeltaEta_jet_jet',
    'N_btags_Tight',
    'jet3_btag',
    'jet3_pt',
    'pT_jet_tag_min_deltaR',
    'pT_jet_jet_min_deltaR',
    'pT_tag_tag_min_deltaR',
    'ptSum_jets_leptons',
    'HT_tags',
    'HT_jets',
    'bjet3_pt',
    'avgDeltaR_tag_tag',
    'avgDeltaR_jet_tag',
    'avgDeltaR_jet_jet',
    'bjet2_btag',
    'jet2_pt',
    'jet1_pt',
    'mass_tag_tag_min_deltaR',
    'mass_jet_tag_min_deltaR',
    'mass_jet_jet_min_deltaR',
    'multiplicity_higgsLikeDijet15',
    'minDeltaR_jet_jet',
    'minDeltaR_tag_tag',
    'bjet2_pt',
    'centrality_tags',
    'twist_tag_tag_max_mass',
    'twist_jet_tag_max_mass',
    'twist_jet_jet_max_mass',
    'bjet1_btag',
    'R1_tag',
    'R1_jet',
    'lepton1_pt',
    'jet2_btag',
    'mass_higgsLikeDijet',
    'mass_tag_tag_max_mass',
    'mass_jet_tag_tag_max_pT',
    'mass_jet_jet_jet_max_pT',
    ]

variables["ge4j_2t"] = [
    'N_btags_Loose',
    'btagDiscriminatorAverage_untagged',
    'ptSum_jets_leptons',
    'jet4_pt',
    'HT_jets',
    'jet3_pt',
    'avgDeltaR_jet_tag',
    'pT_jet_tag_min_deltaR',
    'avgDeltaR_jet_jet',
    'pT_tag_tag_min_deltaR',
    'jet2_pt',
    'pT_jet_jet_min_deltaR',
    'jet1_pt',
    'H0_jet',
    'btagDiscriminatorAverage_tagged',
    'jet3_btag',
    'maxDeltaEta_tag_tag',
    'H4_jet',
    'maxDeltaEta_jet_jet',
    'H2_jet',
    'R1_tag',
    'avgDeltaR_tag_tag',
    'minDeltaR_tag_tag',
    'R4_jet',
    'multiplicity_higgsLikeDijet15',
    'R2_jet',
    'H1_tag',
    'HT_tags',
    'lepton1_pt',
    'H3_jet',
    'aplanarity_jet',
    'D_jet',
    'minDeltaR_jet_jet',
    'jet1_btag',
    'jet2_btag',
    'mass_jet_jet_jet_max_pT',
    'mass_jet_tag_tag_max_pT',
    'mass_jet_tag_min_deltaR',
    'mass_tag_tag_min_deltaR',
    'mass_tag_tag_max_mass'
]

variables["ge4j_3t"] = [
    'blr',
    'blr_transformed',
    'MEM',
    'bjet3_btag',
    'maxDeltaEta_tag_tag',
    'N_btags_Tight',
    'avgDeltaR_tag_tag',
    'bjet2_btag',
    'avgDeltaR_jet_tag',
    'bjet3_pt',
    'avgDeltaR_jet_jet',
    'jet4_pt',
    'N_btags_Loose',
    'maxDeltaEta_jet_jet',
    'jet3_pt',
    'pT_tag_tag_min_deltaR',
    'btagDiscriminatorAverage_untagged',
    'centrality_tags',
    'HT_tags',
    'pT_jet_tag_min_deltaR',
    'HT_jets',
    'ptSum_jets_leptons',
    'R2_jet',
    'H2_jet',
    'D_jet',
    'multiplicity_higgsLikeDijet15',
    'aplanarity_jet',
    'centrality_jets_leps',
    'jet2_pt',
    'pT_jet_jet_min_deltaR',
    'minDeltaR_tag_tag',
    'blr_2b',
    'bjet1_btag',
    'C_jet',
    'H4_jet',
    'sphericity_jet',
    'R4_jet',
    'mass_tag_tag_max_mass',
    'mass_jet_tag_tag_max_pT',
    'mass_jet_tag_min_deltaR',
    'mass_tag_tag_min_deltaR'
    ]

variables["ge4j_ge4t"] = [
    'MEM',
    'maxDeltaEta_tag_tag',
    'blr',
    'blr_transformed',
    'maxDeltaEta_jet_jet',
    'avgDeltaR_tag_tag',
    'mass_tag_tag_min_deltaR',
    'centrality_tags',
    'bjet3_btag',
    'avgDeltaR_jet_tag',
    'D_tag',
    'N_btags_Tight',
    'avgDeltaR_jet_jet',
    'centrality_jets_leps',
    'aplanarity_tag',
    'pT_tag_tag_min_deltaR',
    'H2_tag',
    'R2_tag',
    'bjet4_btag',
    'D_jet',
    'aplanarity_jet',
    'C_tag',
    'H4_tag',
    'sphericity_tag',
    'R4_tag',
    'bjet2_btag',
    'R2_jet',
    'C_jet',
    'H3_tag',
    'sphericity_jet',
    'mass_jet_tag_min_deltaR',
    'transSphericity_tag',
    'mass_jet_jet_min_deltaR',
    'multiplicity_higgsLikeDijet15',
    'HT_tags',
    'H2_jet',
    'btagDiscriminatorAverage_tagged',
    'mass_tag_tag_max_mass',
    'mass_jet_tag_tag_max_pT',
    'pT_jet_tag_min_deltaR'
]

variables["ge4j_ge3t"] = [
    'MEM',
    'blr',
    'blr_transformed',
    'btagDiscriminatorAverage_untagged',
    'N_btags_Loose',
    'ptSum_jets_leptons',
    'pT_jet_tag_min_deltaR',
    'pT_jet_jet_min_deltaR',
    'maxDeltaEta_jet_jet',
    'jet3_btag',
    'HT_jets',
    'pT_tag_tag_min_deltaR',
    'jet1_pt',
    'avgDeltaR_jet_tag',
    'avgDeltaR_jet_jet',
    'R1_jet',
    'jet3_pt',
    'R1_tag',
    'H1_jet',
    'HT_tags',
    'jet2_pt',
    'H1_tag',
    'lepton1_pt',
    'maxDeltaEta_tag_tag',
    'avgDeltaR_tag_tag',
    'minDeltaR_tag_tag',
    'dilepton_pt',
    'mass_jet_tag_min_deltaR',
    'mass_jet_jet_min_deltaR',
    'bjet1_pt',
    'minDeltaR_jet_jet',
    'bjet2_pt',
    'met_pt',
    'twist_jet_tag_max_mass',
    'twist_jet_jet_max_mass',
    'multiplicity_higgsLikeDijet15',
    'mass_tag_tag_max_mass',
    'mass_higgsLikeDijet',
    'mass_tag_tag_min_deltaR',
    'mass_jet_jet_jet_max_pT',
    'mass_jet_tag_tag_max_pT'

    ]

variables["jets"]= [

    "jet1_pt",
    "jet1_eta",
    "jet1_phi",
    "jet1_M",
    "jet1_btag",

    "jet2_pt",
    "jet2_eta",
    "jet2_phi",
    "jet2_M",
    "jet2_btag",

    "jet3_pt",
    "jet3_eta",
    "jet3_phi",
    "jet3_M",
    "jet3_btag",

    "jet4_pt",
    "jet4_eta",
    "jet4_phi",
    "jet4_M",
    "jet4_btag",

    "jet5_pt",
    "jet5_eta",
    "jet5_phi",
    "jet5_M",
    "jet5_btag",

    "jet6_pt",
    "jet6_eta",
    "jet6_phi",
    "jet6_M",
    "jet6_btag",

    "bjet1_pt",
    "bjet1_eta",
    "bjet2_pt",
    "bjet2_eta",
    "bjet3_pt",
    "bjet3_eta",
    "bjet1_btag",
    "bjet2_btag",
    "bjet3_btag",
]

variables["all"] = [
     "lepton1_pt",
     "lepton2_pt",

     "lepton1_eta",
     "lepton2_eta",

      "jet1_pt",
      "jet2_pt",
      "jet3_pt",
      "jet4_pt",
      "jet5_pt",
      "jet6_pt",
      "bjet1_pt",
      "bjet2_pt",
      "bjet3_pt",
      "bjet4_pt",

      "jet1_eta",
      "jet2_eta",
      "jet3_eta",
      "jet4_eta",
      "jet5_eta",
      "jet6_eta",
      "bjet1_eta",
      "bjet2_eta",
      "bjet3_eta",
      "bjet4_eta",

      "jet1_btag",
      "jet2_btag",
      "jet3_btag",
      "jet4_btag",
      "jet5_btag",
      "jet6_btag",
      "bjet1_btag",
      "bjet2_btag",
      "bjet3_btag",
      "bjet4_btag",

     "dilepton_pt",
     "dilepton_eta",
     "dilepton_M",

     "met_pt",
     "met_phi",


     "multiplicity_higgsLikeDijet15",

     "btagDiscriminatorAverage_tagged",
     "btagDiscriminatorAverage_untagged",

     "sphericity_jet",
     "sphericity_tag" ,

     "aplanarity_jet",
     "aplanarity_tag",


     "isotropy_jet",
     "isotropy_tag",

     "C_jet",
     "C_tag",

     "D_jet",
     "D_tag",

     "transSphericity_jet",
     "transSphericity_tag",

     "H0_jet",
     "H1_jet",
     "H2_jet",
     "H3_jet",
     "H4_jet",

     "H0_tag",
     "H1_tag",
     "H2_tag",
     "H3_tag",
     "H4_tag",

     "R1_jet",
     "R2_jet",
     "R3_jet",
     "R4_jet",

     "R1_tag",
     "R2_tag",
     "R3_tag",
     "R4_tag",

     "avgDeltaR_jet_jet",
     "avgDeltaR_jet_tag",
     "avgDeltaR_tag_tag",

     "centrality_jets_leps",
     "centrality_tags",

     "circularity_jet",
     "circularity_tag",

     "mass_higgsLikeDijet",
     "mass_higgsLikeDijet2",


     "mass_jet_jet_min_deltaR",
     "mass_jet_tag_min_deltaR",
     "mass_tag_tag_min_deltaR",
     "mass_tag_tag_max_mass",
     "mass_jet_jet_jet_max_pT",
     "mass_jet_tag_tag_max_pT",

     "maxDeltaEta_jet_jet",
     "maxDeltaEta_tag_tag",

     "median_mass_jet_jet",

     "minDeltaR_jet_jet",
     "minDeltaR_tag_tag",

     "pT_jet_jet_min_deltaR",
     "pT_jet_tag_min_deltaR",
     "pT_tag_tag_min_deltaR",

     "ptSum_jets_leptons",

     "HT_jets",
     "HT_tags",

     "twist_jet_jet_max_mass",
     "twist_jet_tag_max_mass",
     "twist_tag_tag_max_mass",
     "twist_tag_tag_min_deltaR"
]

#variables["ge4j_ge3t"] = list(set(variables["ge4j_ge4t"][,] + variables["ge4j_3t"][,]))
#variables["ge4j_ge3t"] = list(set(variables["ge4j_ge4t"][,] + variables["ge4j_3t"][,] + variables["jets"]))
#!! variables["ge4j_ge3t"] = ["jet1_pt", "jet2_pt"] #!!!!

all_variables = set( [v for key in variables for v in variables[key] ] )
