variables = {}
variables["ge4j_ge3t"] = [
    'Evt_Deta_JetsAverage',
        'Evt_Deta_TaggedJetsAverage',
        'Evt_Deta_maxDetaJetJet',
        'Evt_Deta_maxDetaJetTag',
        'Evt_Deta_maxDetaTagTag',
        'Evt_Dr_JetsAverage',
        'Evt_Dr_TaggedJetsAverage',
        'Evt_Dr_closestTo91TaggedJets',
        'Evt_Dr_maxDrJets',
        'Evt_Dr_maxDrTaggedJets',
        'Evt_Dr_minDrJets',
        'Evt_Dr_minDrLepJet',
        'Evt_Dr_minDrLepTag',
        'Evt_Dr_minDrTaggedJets',
        'Evt_E_JetsAverage',
        'Evt_E_TaggedJetsAverage',
        'Evt_Eta_JetsAverage',
        'Evt_Eta_TaggedJetsAverage',
        'Evt_HT',
        'Evt_HT_jets',
        'Evt_HT_tags',
        'Evt_HT_wo_MET',
        'Evt_JetPt_over_JetE',
        'Evt_M2_JetsAverage',
        'Evt_M2_TaggedJetsAverage',
        'Evt_M2_closestTo125TaggedJets',
        'Evt_M2_closestTo91TaggedJets',
        'Evt_M2_minDrJets',
        'Evt_M2_minDrTaggedJets',
        'Evt_M3',
        'Evt_MET',
        'Evt_MET_Phi',
        'Evt_MET_Pt',
        'Evt_MHT',
        'Evt_MTW',
        'Evt_M_JetsAverage',
        'Evt_M_TaggedJetsAverage',
        'Evt_M_Total',
        'Evt_M_minDrLepJet',
        'Evt_M_minDrLepTag',
        'Evt_Pt_JetsAverage',
        'Evt_Pt_TaggedJetsAverage',
        'Evt_Pt_minDrJets',
        'Evt_Pt_minDrTaggedJets',
        'Evt_TaggedJetPt_over_TaggedJetE',
        'Evt_aplanarity',
        'Evt_aplanarity_jets',
        'Evt_aplanarity_tags',
        'Evt_blr',
        'Evt_blr_transformed',
        'Evt_btagValue_avg',
        'Evt_btagValue_avg_tagged',
        'Evt_btagValue_dev',
        'Evt_btagValue_dev_tagged',
        'Evt_btagValue_min',
        'Evt_btagValue_min_tagged',
        'Evt_h0',
        'Evt_h1',
        'Evt_h2',
        'Evt_h3',
        'Evt_sphericity',
        'Evt_sphericity_jets',
        'Evt_sphericity_tags',
        'Evt_transverse_sphericity',
        'Evt_transverse_sphericity_jets',
        'Evt_transverse_sphericity_tags',


    'N_BTagsL',
    'N_BTagsM',
    'N_BTagsT',
    'N_LooseJets',
    #'btagValue[0]',
    #'btagValue[1]',
    #'btagValue[2]',
    #'btagValue[3]',
    #'btagValue[4]',
    #'btagValue[5]',
    #'Jet_M[0]',
    #'Jet_M[1]',
    #'Jet_M[2]',
    #'Jet_M[3]',
    #'Jet_M[4]',
    #'Jet_M[5]',
    #'Jet_Phi[0]',
    #'Jet_Phi[1]',
    #'Jet_Phi[2]',
    #'Jet_Phi[3]',
    #'Jet_Phi[4]',
    #'Jet_Phi[5]',
    #'Jet_Pt[0]',
    #'Jet_Pt[1]',
    #'Jet_Pt[2]',
    #'Jet_Pt[3]',
    #'Jet_Pt[4]',
    #'Jet_Pt[5]',
    #'TaggedJet_E[0]',
    #'TaggedJet_E[1]',
    #'TaggedJet_E[2]',
    #'TaggedJet_E[3]',
    #'TaggedJet_Eta[0]',
    #'TaggedJet_Eta[1]',
    #'TaggedJet_Eta[2]',
    #'TaggedJet_Eta[3]',
    #'TaggedJet_M[0]',
    #'TaggedJet_M[1]',
    #'TaggedJet_M[2]',
    #'TaggedJet_M[3]',
    #'TaggedJet_Phi[0]',
    #'TaggedJet_Phi[1]',
    #'TaggedJet_Phi[2]',
    #'TaggedJet_Phi[3]',
    #'TaggedJet_Pt[0]',
    #'TaggedJet_Pt[1]',
    #'TaggedJet_Pt[2]',
    #'TaggedJet_Pt[3]',
    #'Jet_E[0]',
    #'Jet_E[1]',
    #'Jet_E[2]',
    #'Jet_E[3]',
    #'Jet_E[4]',
    #'Jet_E[5]',
    #'Jet_Eta[0]',
    #'Jet_Eta[1]',
    #'Jet_Eta[2]',
    #'Jet_Eta[3]',
    #'Jet_Eta[4]',
    #'Jet_Eta[5]',

    
    ##################################
    # X boson stuff
    ##################################
    "RecoX_B1_Eta",
    "RecoX_B2_Eta",
    "RecoX_B1_Phi",
    "RecoX_B2_Phi",
    "RecoX_B1_btagValue",
    "RecoX_B2_btagValue",
    "RecoX_B1_M",
    "RecoX_B2_M",
    "RecoX_B1_E",
    "RecoX_B2_E",
    "RecoX_B1_Pt",
    "RecoX_B2_Pt",
    "RecoX_B1_idx",
    "RecoX_B2_idx",
    "N_Jets",
    "N_BTagsM",
    "RecoX_X_Pt",
    "RecoX_X_Eta",
    "RecoX_X_M",
    "RecoX_X_E",
    "RecoX_X_openingAngle",
    "RecoX_X_dPhi",
    "RecoX_X_dEta",
    "RecoX_X_dPt",
    "RecoX_X_dR",
    #"RecoX_X_dKin",



    ###############################
    #lepton variables
    ###############################
    "TightLepton_E_0",
    "TightLepton_Eta_0",
    "TightLepton_M_0",
    "TightLepton_Phi_0",
    "TightLepton_Pt_0",

    "RecoX_B1_dEta_lept",
    "RecoX_B2_dEta_lept",
    "RecoX_B1_dPhi_lept",
    "RecoX_B2_dPhi_lept",
    "RecoX_B1_dR_lept",
    "RecoX_B2_dR_lept",
    "RecoX_X_btagAverage",

    "RecoX_X_dEta_lept",
    "RecoX_X_dPhi_lept",
    "RecoX_X_dR_lept",



    #additional variables, if X boson stuff does not work

    ##########################
    #dnnZ - Reco variables
    ##########################

    #"dnnZ_ft_RecoX_B1_Eta",
    #"dnnZ_ft_RecoX_B1_Phi",
    #"dnnZ_ft_RecoX_B1_Pt",
    #"dnnZ_ft_RecoX_B1_E",
    #"dnnZ_ft_RecoX_B1_M",
    #"dnnZ_ft_RecoX_B1_btagValue",
    #"dnnZ_ft_RecoX_B1_idx",
    #"dnnZ_ft_RecoX_B1_logPt",
    #"dnnZ_ft_RecoX_B1_logE",
    #"dnnZ_ft_RecoX_B2_Eta",
    #"dnnZ_ft_RecoX_B2_Phi",
    #"dnnZ_ft_RecoX_B2_Pt",
    #"dnnZ_ft_RecoX_B2_E",
    #"dnnZ_ft_RecoX_B2_M",
    #"dnnZ_ft_RecoX_B2_btagValue",
    #"dnnZ_ft_RecoX_B2_idx",
    #"dnnZ_ft_RecoX_B2_logPt",
    #"dnnZ_ft_RecoX_B2_logE",
    #"dnnZ_ft_RecoX_X_Pt",
    #"dnnZ_ft_RecoX_X_Eta",
    #"dnnZ_ft_RecoX_X_M",
    #"dnnZ_ft_RecoX_X_logM",
    #"dnnZ_ft_RecoX_X_E",
    #"dnnZ_ft_RecoX_X_logE",
    #"dnnZ_ft_RecoX_X_logPt",
    #"dnnZ_ft_RecoX_X_openingAngle",
    #"dnnZ_ft_RecoX_dR",
    #"dnnZ_ft_RecoX_dPhi",
    #"dnnZ_ft_RecoX_dEta",
    #"dnnZ_ft_RecoX_dPt",
    #"dnnZ_ft_RecoX_X_Delta_R3D",
    #"dnnZ_ft_RecoX_X_Boosted1_Pt",
    #"dnnZ_ft_RecoX_X_Boosted1_Eta",
    #"dnnZ_ft_RecoX_X_Boosted1_logPt",
    #"dnnZ_ft_RecoX_X_Boosted2_Pt",
    #"dnnZ_ft_RecoX_X_Boosted2_Eta",
    #"dnnZ_ft_RecoX_X_Boosted2_logPt",
    #"dnnZ_ft_RecoX_X_Angle",
    #"dnnZ_ft_RecoX_DNNOutput",
    #"dnnZ_ft_RecoX_squaredDNNOutput",
    #"dnnZ_ft_RecoX_transformedDNNOutput",




    ##########################
    #dnnH - Reco variables
    ##########################

    #"dnnH_ft_RecoX_B1_Eta",
    #"dnnH_ft_RecoX_B1_Phi",
    #"dnnH_ft_RecoX_B1_Pt",
    #"dnnH_ft_RecoX_B1_E",
    #"dnnH_ft_RecoX_B1_M",
    #"dnnH_ft_RecoX_B1_btagValue",
    #"dnnH_ft_RecoX_B1_idx",
    #"dnnH_ft_RecoX_B1_logPt",
    #"dnnH_ft_RecoX_B1_logE",
    #"dnnH_ft_RecoX_B2_Eta",
    #"dnnH_ft_RecoX_B2_Phi",
    #"dnnH_ft_RecoX_B2_Pt",
    #"dnnH_ft_RecoX_B2_E",
    #"dnnH_ft_RecoX_B2_M",
    #"dnnH_ft_RecoX_B2_btagValue",
    #"dnnH_ft_RecoX_B2_idx",
    #"dnnH_ft_RecoX_B2_logPt",
    #"dnnH_ft_RecoX_B2_logE",
    #"dnnH_ft_RecoX_X_Pt",
    #"dnnH_ft_RecoX_X_Eta",
    #"dnnH_ft_RecoX_X_M",
    #"dnnH_ft_RecoX_X_logM",
    #"dnnH_ft_RecoX_X_E",
    #"dnnH_ft_RecoX_X_logE",
    #"dnnH_ft_RecoX_X_logPt",
    #"dnnH_ft_RecoX_X_openingAngle",
    #"dnnH_ft_RecoX_dR",
    #"dnnH_ft_RecoX_dPhi",
    #"dnnH_ft_RecoX_dEta",
    #"dnnH_ft_RecoX_dPt",
    #"dnnH_ft_RecoX_X_Delta_R3D",
    #"dnnH_ft_RecoX_X_Boosted1_Pt",
    #"dnnH_ft_RecoX_X_Boosted1_Eta",
    #"dnnH_ft_RecoX_X_Boosted1_logPt",
    #"dnnH_ft_RecoX_X_Boosted2_Pt",
    #"dnnH_ft_RecoX_X_Boosted2_Eta",
    #"dnnH_ft_RecoX_X_Boosted2_logPt",
    #"dnnH_ft_RecoX_X_Angle",
    #"dnnH_ft_RecoX_DNNOutput",
    #"dnnH_ft_RecoX_squaredDNNOutput",
    #"dnnH_ft_RecoX_transformedDNNOutput",


    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))

