variables = {}
variables["ge4j_ge3t"] = [
#     'Evt_CSV_avg',
#     'Evt_CSV_avg_tagged',
#     'Evt_CSV_dev',
#     'Evt_CSV_dev_tagged',
#     'Evt_CSV_min',
#     'Evt_CSV_min_tagged',
    'Evt_Deta_JetsAverage',
    # 'Evt_Deta_TaggedJetsAverage',
    'Evt_Deta_maxDetaJetJet',
    # 'Evt_Deta_maxDetaJetTag',
    # 'Evt_Deta_maxDetaTagTag',
    'Evt_Dr_JetsAverage',
    # 'Evt_Dr_TaggedJetsAverage',
    'Evt_Dr_maxDrJets',
    # 'Evt_Dr_maxDrTaggedJets',
    'Evt_Dr_minDrJets',
    'Evt_Dr_minDrLepJet',
    'Evt_Dr_minDrLepTag',
    # 'Evt_Dr_minDrTaggedJets',
    'Evt_E_JetsAverage',
    'Evt_E_TaggedJetsAverage',
    'Evt_Eta_JetsAverage',
    # 'Evt_Eta_TaggedJetsAverage',
    'Evt_HT',
    # 'Evt_HT_jets',
    # 'Evt_HT_tags',
    # 'Evt_HT_wo_MET',
    'Evt_JetPt_over_JetE',
    'Evt_M2_JetsAverage',
    # 'Evt_M2_TaggedJetsAverage',
    # 'Evt_M2_closestTo125TaggedJets',
    # 'Evt_M2_closestTo91TaggedJets',
    'Evt_M2_minDrJets',
    # 'Evt_M2_minDrTaggedJets',
    'Evt_M3',
    # 'Evt_M3_oneTagged',
    'Evt_MHT',
    'Evt_MTW',
    'Evt_M_JetsAverage',
    # 'Evt_M_TaggedJetsAverage',
    'Evt_M_Total',
    'Evt_M_minDrLepJet',
    'Evt_M_minDrLepTag',
    'Evt_Pt_JetsAverage',
    # 'Evt_Pt_TaggedJetsAverage',
    'Evt_Pt_minDrJets',
    # 'Evt_Pt_minDrTaggedJets',
    # 'Evt_TaggedJetPt_over_TaggedJetE',
    'Evt_aplanarity',
    # 'Evt_aplanarity_jets',
    # 'Evt_aplanarity_tags',
    # 'Evt_blr',
    # 'Evt_blr_transformed',
    'Evt_h0',
    'Evt_h1',
    'Evt_h2',
    'Evt_h3',
    'Evt_sphericity',
    'Evt_sphericity_jets',
    # 'Evt_sphericity_tags',
    'Evt_transverse_sphericity',
    'Evt_transverse_sphericity_jets',
    # 'Evt_transverse_sphericity_tags',
    # 'N_BTagsL',
    # 'N_BTagsT',
    #'N_ForwardJets',
    'N_Jets',
    #'N_LooseJets',
    'CSV[0]',
    'CSV[1]',
    'CSV[2]',
    'CSV[3]',
    'Jet_CSV[0]',
    'Jet_CSV[1]',
    'Jet_CSV[2]',
    'Jet_CSV[3]',
    # 'Jet_Charge[0]',
    # 'Jet_Charge[1]',
    # 'Jet_Charge[2]',
    # 'Jet_Charge[3]',
    # 'Jet_E[0]',
    # 'Jet_E[1]',
    # 'Jet_E[2]',
    # 'Jet_E[3]',
    'Jet_Eta[0]',
    'Jet_Eta[1]',
    'Jet_Eta[2]',
    'Jet_Eta[3]',
    # 'Jet_M[0]',
    # 'Jet_M[1]',
    # 'Jet_M[2]',
    # 'Jet_M[3]',
    'Jet_Phi[0]',
    'Jet_Phi[1]',
    'Jet_Phi[2]',
    'Jet_Phi[3]',
    'Jet_Pt[0]',
    'Jet_Pt[1]',
    'Jet_Pt[2]', 
    ]



all_variables = list(set( [v for key in variables for v in variables[key] ] ))
