recolist_H = [
    "dnnH_ft_RecoX_jet1_btagValue",
    "dnnH_ft_RecoX_jet2_btagValue",
    "dnnH_ft_RecoX_jet1_Pt",
    "dnnH_ft_RecoX_jet2_Pt",
    "dnnH_ft_RecoX_jet1_M",
    "dnnH_ft_RecoX_jet2_M",
    "dnnH_ft_RecoX_jet1_E",
    "dnnH_ft_RecoX_jet2_E",
    "dnnH_ft_RecoX_jet1_Eta",
    "dnnH_ft_RecoX_jet2_Eta",
    "dnnH_ft_RecoX_jet1_Phi",
    "dnnH_ft_RecoX_jet2_Phi",
    "dnnH_ft_RecoX_jet1_idx",
    "dnnH_ft_RecoX_jet2_idx",
    "dnnH_ft_RecoX_X_dPhi",
    "dnnH_ft_RecoX_X_dEta",
    "dnnH_ft_RecoX_X_dPt",
    "dnnH_ft_RecoX_X_dR",
    "dnnH_ft_RecoX_X_dKin",
    "dnnH_ft_RecoX_X_Pt",
    "dnnH_ft_RecoX_X_Eta",
    "dnnH_ft_RecoX_X_M",
    "dnnH_ft_RecoX_X_E",
    #"dnnH_ft_RecoX_jet1_logPt",
    #"dnnH_ft_RecoX_jet1_logM",
    #"dnnH_ft_RecoX_jet1_logE",
    #"dnnH_ft_RecoX_jet2_logPt",
    #"dnnH_ft_RecoX_jet2_logM",
    #"dnnH_ft_RecoX_jet2_logE",
    #"dnnH_ft_RecoX_X_logPt",
    #"dnnH_ft_RecoX_X_logM",
    #"dnnH_ft_RecoX_X_logE",
    "dnnH_ft_RecoX_X_openingAngle",
    #"dnnH_ft_RecoX_jet1_Pt_boosted",
    #"dnnH_ft_RecoX_jet1_M_boosted",
    #"dnnH_ft_RecoX_jet1_E_boosted",
    #"dnnH_ft_RecoX_jet1_Eta_boosted",
    #"dnnH_ft_RecoX_jet1_Phi_boosted",
    #"dnnH_ft_RecoX_jet1_logPt_boosted",
    #"dnnH_ft_RecoX_jet2_Pt_boosted",
    #"dnnH_ft_RecoX_jet2_M_boosted",
    #"dnnH_ft_RecoX_jet2_E_boosted",
    #"dnnH_ft_RecoX_jet2_Eta_boosted",
    #"dnnH_ft_RecoX_jet2_Phi_boosted",
    #"dnnH_ft_RecoX_jet2_logPt_boosted",
    #"dnnH_ft_RecoX_X_Pt_boosted",
    #"dnnH_ft_RecoX_X_M_boosted",
    #"dnnH_ft_RecoX_X_E_boosted",
    #"dnnH_ft_RecoX_X_Eta_boosted",
    #"dnnH_ft_RecoX_X_Phi_boosted",
    #"dnnH_ft_RecoX_X_logPt_boosted",
    #"dnnH_ft_RecoX_dPhi_boosted",
    #"dnnH_ft_RecoX_dEta_boosted",
    #"dnnH_ft_RecoX_dR_boosted",
    #"dnnH_ft_RecoX_X_Chi2",
    "dnnH_ft_RecoX_DNNOutput",
    "dnnH_ft_RecoX_squaredDNNOutput",
    "dnnH_ft_RecoX_transformedDNNOutput",

    ]

recolist_Z = [
    "dnnZ_ft_RecoX_jet1_btagValue",
    "dnnZ_ft_RecoX_jet2_btagValue",
    "dnnZ_ft_RecoX_jet1_Pt",
    "dnnZ_ft_RecoX_jet2_Pt",
    "dnnZ_ft_RecoX_jet1_M",
    "dnnZ_ft_RecoX_jet2_M",
    "dnnZ_ft_RecoX_jet1_E",
    "dnnZ_ft_RecoX_jet2_E",
    "dnnZ_ft_RecoX_jet1_Eta",
    "dnnZ_ft_RecoX_jet2_Eta",
    "dnnZ_ft_RecoX_jet1_Phi",
    "dnnZ_ft_RecoX_jet2_Phi",
    "dnnZ_ft_RecoX_jet1_idx",
    "dnnZ_ft_RecoX_jet2_idx",
    "dnnZ_ft_RecoX_X_dPhi",
    "dnnZ_ft_RecoX_X_dEta",
    "dnnZ_ft_RecoX_X_dPt",
    "dnnZ_ft_RecoX_X_dR",
    "dnnZ_ft_RecoX_X_dKin",
    "dnnZ_ft_RecoX_X_Pt",
    "dnnZ_ft_RecoX_X_Eta",
    "dnnZ_ft_RecoX_X_M",
    "dnnZ_ft_RecoX_X_E",
    #"dnnZ_ft_RecoX_jet1_logPt",
    #"dnnZ_ft_RecoX_jet1_logM",
    #"dnnZ_ft_RecoX_jet1_logE",
    #"dnnZ_ft_RecoX_jet2_logPt",
    #"dnnZ_ft_RecoX_jet2_logM",
    #"dnnZ_ft_RecoX_jet2_logE",
    #"dnnZ_ft_RecoX_X_logPt",
    #"dnnZ_ft_RecoX_X_logM",
    #"dnnZ_ft_RecoX_X_logE",
    "dnnZ_ft_RecoX_X_openingAngle",
    #"dnnZ_ft_RecoX_jet1_Pt_boosted",
    #"dnnZ_ft_RecoX_jet1_M_boosted",
    #"dnnZ_ft_RecoX_jet1_E_boosted",
    #"dnnZ_ft_RecoX_jet1_Eta_boosted",
    #"dnnZ_ft_RecoX_jet1_Phi_boosted",
    #"dnnZ_ft_RecoX_jet1_logPt_boosted",
    #"dnnZ_ft_RecoX_jet2_Pt_boosted",
    #"dnnZ_ft_RecoX_jet2_M_boosted",
    #"dnnZ_ft_RecoX_jet2_E_boosted",
    #"dnnZ_ft_RecoX_jet2_Eta_boosted",
    #"dnnZ_ft_RecoX_jet2_Phi_boosted",
    #"dnnZ_ft_RecoX_jet2_logPt_boosted",
    #"dnnZ_ft_RecoX_X_Pt_boosted",
    #"dnnZ_ft_RecoX_X_M_boosted",
    #"dnnZ_ft_RecoX_X_E_boosted",
    #"dnnZ_ft_RecoX_X_Eta_boosted",
    #"dnnZ_ft_RecoX_X_Phi_boosted",
    #"dnnZ_ft_RecoX_X_logPt_boosted",
    #"dnnZ_ft_RecoX_dPhi_boosted",
    #"dnnZ_ft_RecoX_dEta_boosted",
    #"dnnZ_ft_RecoX_dR_boosted",
    #"dnnZ_ft_RecoX_X_Chi2",
    "dnnZ_ft_RecoX_DNNOutput",
    "dnnZ_ft_RecoX_squaredDNNOutput",
    "dnnZ_ft_RecoX_transformedDNNOutput",

    ]

recolist_bb = [
    "dnnbb_ft_RecoX_jet1_btagValue",
    "dnnbb_ft_RecoX_jet2_btagValue",
    "dnnbb_ft_RecoX_jet1_Pt",
    "dnnbb_ft_RecoX_jet2_Pt",
    "dnnbb_ft_RecoX_jet1_M",
    "dnnbb_ft_RecoX_jet2_M",
    "dnnbb_ft_RecoX_jet1_E",
    "dnnbb_ft_RecoX_jet2_E",
    "dnnbb_ft_RecoX_jet1_Eta",
    "dnnbb_ft_RecoX_jet2_Eta",
    "dnnbb_ft_RecoX_jet1_Phi",
    "dnnbb_ft_RecoX_jet2_Phi",
    "dnnbb_ft_RecoX_jet1_idx",
    "dnnbb_ft_RecoX_jet2_idx",
    "dnnbb_ft_RecoX_X_dPhi",
    "dnnbb_ft_RecoX_X_dEta",
    "dnnbb_ft_RecoX_X_dPt",
    "dnnbb_ft_RecoX_X_dR",
    "dnnbb_ft_RecoX_X_dKin",
    "dnnbb_ft_RecoX_X_Pt",
    "dnnbb_ft_RecoX_X_Eta",
    "dnnbb_ft_RecoX_X_M",
    "dnnbb_ft_RecoX_X_E",
    #"dnnbb_ft_RecoX_jet1_logPt",
    #"dnnbb_ft_RecoX_jet1_logM",
    #"dnnbb_ft_RecoX_jet1_logE",
    #"dnnbb_ft_RecoX_jet2_logPt",
    #"dnnbb_ft_RecoX_jet2_logM",
    #"dnnbb_ft_RecoX_jet2_logE",
    #"dnnbb_ft_RecoX_X_logPt",
    #"dnnbb_ft_RecoX_X_logM",
    #"dnnbb_ft_RecoX_X_logE",
    "dnnbb_ft_RecoX_X_openingAngle",
    #"dnnbb_ft_RecoX_jet1_Pt_boosted",
    #"dnnbb_ft_RecoX_jet1_M_boosted",
    #"dnnbb_ft_RecoX_jet1_E_boosted",
    #"dnnbb_ft_RecoX_jet1_Eta_boosted",
    #"dnnbb_ft_RecoX_jet1_Phi_boosted",
    #"dnnbb_ft_RecoX_jet1_logPt_boosted",
    #"dnnbb_ft_RecoX_jet2_Pt_boosted",
    #"dnnbb_ft_RecoX_jet2_M_boosted",
    #"dnnbb_ft_RecoX_jet2_E_boosted",
    #"dnnbb_ft_RecoX_jet2_Eta_boosted",
    #"dnnbb_ft_RecoX_jet2_Phi_boosted",
    #"dnnbb_ft_RecoX_jet2_logPt_boosted",
    #"dnnbb_ft_RecoX_X_Pt_boosted",
    #"dnnbb_ft_RecoX_X_M_boosted",
    #"dnnbb_ft_RecoX_X_E_boosted",
    #"dnnbb_ft_RecoX_X_Eta_boosted",
    #"dnnbb_ft_RecoX_X_Phi_boosted",
    #"dnnbb_ft_RecoX_X_logPt_boosted",
    #"dnnbb_ft_RecoX_dPhi_boosted",
    #"dnnbb_ft_RecoX_dEta_boosted",
    #"dnnbb_ft_RecoX_dR_boosted",
    #"dnnbb_ft_RecoX_X_Chi2",
    "dnnbb_ft_RecoX_DNNOutput",
    "dnnbb_ft_RecoX_squaredDNNOutput",
    "dnnbb_ft_RecoX_transformedDNNOutput",

    ]

recolist_cc = [
    "dnncc_ft_RecoX_jet1_btagValue",
    "dnncc_ft_RecoX_jet2_btagValue",
    "dnncc_ft_RecoX_jet1_Pt",
    "dnncc_ft_RecoX_jet2_Pt",
    "dnncc_ft_RecoX_jet1_M",
    "dnncc_ft_RecoX_jet2_M",
    "dnncc_ft_RecoX_jet1_E",
    "dnncc_ft_RecoX_jet2_E",
    "dnncc_ft_RecoX_jet1_Eta",
    "dnncc_ft_RecoX_jet2_Eta",
    "dnncc_ft_RecoX_jet1_Phi",
    "dnncc_ft_RecoX_jet2_Phi",
    "dnncc_ft_RecoX_jet1_idx",
    "dnncc_ft_RecoX_jet2_idx",
    "dnncc_ft_RecoX_X_dPhi",
    "dnncc_ft_RecoX_X_dEta",
    "dnncc_ft_RecoX_X_dPt",
    "dnncc_ft_RecoX_X_dR",
    "dnncc_ft_RecoX_X_dKin",
    "dnncc_ft_RecoX_X_Pt",
    "dnncc_ft_RecoX_X_Eta",
    "dnncc_ft_RecoX_X_M",
    "dnncc_ft_RecoX_X_E",
    #"dnncc_ft_RecoX_jet1_logPt",
    #"dnncc_ft_RecoX_jet1_logM",
    #"dnncc_ft_RecoX_jet1_logE",
    #"dnncc_ft_RecoX_jet2_logPt",
    #"dnncc_ft_RecoX_jet2_logM",
    #"dnncc_ft_RecoX_jet2_logE",
    #"dnncc_ft_RecoX_X_logPt",
    #"dnncc_ft_RecoX_X_logM",
    #"dnncc_ft_RecoX_X_logE",
    "dnncc_ft_RecoX_X_openingAngle",
    #"dnncc_ft_RecoX_jet1_Pt_boosted",
    #"dnncc_ft_RecoX_jet1_M_boosted",
    #"dnncc_ft_RecoX_jet1_E_boosted",
    #"dnncc_ft_RecoX_jet1_Eta_boosted",
    #"dnncc_ft_RecoX_jet1_Phi_boosted",
    #"dnncc_ft_RecoX_jet1_logPt_boosted",
    #"dnncc_ft_RecoX_jet2_Pt_boosted",
    #"dnncc_ft_RecoX_jet2_M_boosted",
    #"dnncc_ft_RecoX_jet2_E_boosted",
    #"dnncc_ft_RecoX_jet2_Eta_boosted",
    #"dnncc_ft_RecoX_jet2_Phi_boosted",
    #"dnncc_ft_RecoX_jet2_logPt_boosted",
    #"dnncc_ft_RecoX_X_Pt_boosted",
    #"dnncc_ft_RecoX_X_M_boosted",
    #"dnncc_ft_RecoX_X_E_boosted",
    #"dnncc_ft_RecoX_X_Eta_boosted",
    #"dnncc_ft_RecoX_X_Phi_boosted",
    #"dnncc_ft_RecoX_X_logPt_boosted",
    #"dnncc_ft_RecoX_dPhi_boosted",
    #"dnncc_ft_RecoX_dEta_boosted",
    #"dnncc_ft_RecoX_dR_boosted",
    #"dnncc_ft_RecoX_X_Chi2",
    "dnncc_ft_RecoX_DNNOutput",
    "dnncc_ft_RecoX_squaredDNNOutput",
    "dnncc_ft_RecoX_transformedDNNOutput",

    ]


recolist_ttTobb = [
    "dnnttTobb_ft_RecoX_jet1_btagValue",
    "dnnttTobb_ft_RecoX_jet2_btagValue",
    "dnnttTobb_ft_RecoX_jet1_Pt",
    "dnnttTobb_ft_RecoX_jet2_Pt",
    "dnnttTobb_ft_RecoX_jet1_M",
    "dnnttTobb_ft_RecoX_jet2_M",
    "dnnttTobb_ft_RecoX_jet1_E",
    "dnnttTobb_ft_RecoX_jet2_E",
    "dnnttTobb_ft_RecoX_jet1_Eta",
    "dnnttTobb_ft_RecoX_jet2_Eta",
    "dnnttTobb_ft_RecoX_jet1_Phi",
    "dnnttTobb_ft_RecoX_jet2_Phi",
    "dnnttTobb_ft_RecoX_jet1_idx",
    "dnnttTobb_ft_RecoX_jet2_idx",
    "dnnttTobb_ft_RecoX_X_dPhi",
    "dnnttTobb_ft_RecoX_X_dEta",
    "dnnttTobb_ft_RecoX_X_dPt",
    "dnnttTobb_ft_RecoX_X_dR",
    "dnnttTobb_ft_RecoX_X_dKin",
    "dnnttTobb_ft_RecoX_X_Pt",
    "dnnttTobb_ft_RecoX_X_Eta",
    "dnnttTobb_ft_RecoX_X_M",
    "dnnttTobb_ft_RecoX_X_E",
    #"dnnttTobb_ft_RecoX_jet1_logPt",
    #"dnnttTobb_ft_RecoX_jet1_logM",
    #"dnnttTobb_ft_RecoX_jet1_logE",
    #"dnnttTobb_ft_RecoX_jet2_logPt",
    #"dnnttTobb_ft_RecoX_jet2_logM",
    #"dnnttTobb_ft_RecoX_jet2_logE",
    #"dnnttTobb_ft_RecoX_X_logPt",
    #"dnnttTobb_ft_RecoX_X_logM",
    #"dnnttTobb_ft_RecoX_X_logE",
    "dnnttTobb_ft_RecoX_X_openingAngle",
    #"dnnttTobb_ft_RecoX_jet1_Pt_boosted",
    #"dnnttTobb_ft_RecoX_jet1_M_boosted",
    #"dnnttTobb_ft_RecoX_jet1_E_boosted",
    #"dnnttTobb_ft_RecoX_jet1_Eta_boosted",
    #"dnnttTobb_ft_RecoX_jet1_Phi_boosted",
    #"dnnttTobb_ft_RecoX_jet1_logPt_boosted",
    #"dnnttTobb_ft_RecoX_jet2_Pt_boosted",
    #"dnnttTobb_ft_RecoX_jet2_M_boosted",
    #"dnnttTobb_ft_RecoX_jet2_E_boosted",
    #"dnnttTobb_ft_RecoX_jet2_Eta_boosted",
    #"dnnttTobb_ft_RecoX_jet2_Phi_boosted",
    #"dnnttTobb_ft_RecoX_jet2_logPt_boosted",
    #"dnnttTobb_ft_RecoX_X_Pt_boosted",
    #"dnnttTobb_ft_RecoX_X_M_boosted",
    #"dnnttTobb_ft_RecoX_X_E_boosted",
    #"dnnttTobb_ft_RecoX_X_Eta_boosted",
    #"dnnttTobb_ft_RecoX_X_Phi_boosted",
    #"dnnttTobb_ft_RecoX_X_logPt_boosted",
    #"dnnttTobb_ft_RecoX_dPhi_boosted",
    #"dnnttTobb_ft_RecoX_dEta_boosted",
    #"dnnttTobb_ft_RecoX_dR_boosted",
    #"dnnttTobb_ft_RecoX_X_Chi2",
    "dnnttTobb_ft_RecoX_DNNOutput",
    "dnnttTobb_ft_RecoX_squaredDNNOutput",
    "dnnttTobb_ft_RecoX_transformedDNNOutput",

    ]

kinlist = [
    'btagValue[0]',
    'btagValue[1]',
    'btagValue[2]',
    'btagValue[3]',
    'btagValue[4]',
    'btagValue[5]',
    #'Jet_btagValue[0]',
    #'Jet_btagValue[1]',
    #'Jet_btagValue[2]',
    #'Jet_btagValue[3]',
    #'Jet_btagValue[4]',
    #'Jet_btagValue[5]',
    #'Jet_DeepJet_b[0]',
    #'Jet_DeepJet_b[1]',
    #'Jet_DeepJet_b[2]',
    #'Jet_DeepJet_b[3]',
    #'Jet_DeepJet_b[4]',
    #'Jet_DeepJet_b[5]',
    #'Jet_DeepJet_bb[0]',
    #'Jet_DeepJet_bb[1]',
    #'Jet_DeepJet_bb[2]',
    #'Jet_DeepJet_bb[3]',
    #'Jet_DeepJet_bb[4]',
    #'Jet_DeepJet_bb[5]',
    #'Jet_DeepJet_c[0]',
    #'Jet_DeepJet_c[1]',
    #'Jet_DeepJet_c[2]',
    #'Jet_DeepJet_c[3]',
    #'Jet_DeepJet_c[4]',
    #'Jet_DeepJet_c[5]',
    #'Jet_DeepJet_g[0]',
    #'Jet_DeepJet_g[1]',
    #'Jet_DeepJet_g[2]',
    #'Jet_DeepJet_g[3]',
    #'Jet_DeepJet_g[4]',
    #'Jet_DeepJet_g[5]',
    #'Jet_DeepJet_lepb[0]',
    #'Jet_DeepJet_lepb[1]',
    #'Jet_DeepJet_lepb[2]',
    #'Jet_DeepJet_lepb[3]',
    #'Jet_DeepJet_lepb[4]',
    #'Jet_DeepJet_lepb[5]',
    #'Jet_DeepJet_uds[0]',
    #'Jet_DeepJet_uds[1]',
    #'Jet_DeepJet_uds[2]',
    #'Jet_DeepJet_uds[3]',
    #'Jet_DeepJet_uds[4]',
    #'Jet_DeepJet_uds[5]',
    'Jet_E[0]',
    'Jet_E[1]',
    'Jet_E[2]',
    'Jet_E[3]',
    'Jet_E[4]',
    'Jet_E[5]',
    'Jet_Eta[0]',
    'Jet_Eta[1]',
    'Jet_Eta[2]',
    'Jet_Eta[3]',
    'Jet_Eta[4]',
    'Jet_Eta[5]',
    'Jet_M[0]',
    'Jet_M[1]',
    'Jet_M[2]',
    'Jet_M[3]',
    'Jet_M[4]',
    'Jet_M[5]',
    'Jet_Phi[0]',
    'Jet_Phi[1]',
    'Jet_Phi[2]',
    'Jet_Phi[3]',
    'Jet_Phi[4]',
    'Jet_Phi[5]',
    'Jet_Pt[0]',
    'Jet_Pt[1]',
    'Jet_Pt[2]',
    'Jet_Pt[3]',
    'Jet_Pt[4]',
    'Jet_Pt[5]',
    'TightLepton_E[0]',
    'TightLepton_Eta[0]',
    'TightLepton_M[0]',
    'TightLepton_Phi[0]',
    'TightLepton_Pt[0]',
    ]

evtlist = [
    'Evt_Deta_JetsAverage',
    'Evt_Deta_TaggedJetsAverage',
    'Evt_Deta_maxDetaJetJet',
    'Evt_Deta_maxDetaJetTag',
    'Evt_Deta_maxDetaTagTag',
    'Evt_Dr_JetsAverage',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_Dr_closestTo91TaggedJets',
    'Evt_Dr_maxDrJets',
    'Evt_Dr_maxDrTaggedJets',
    'Evt_Dr_minDrJets',
    'Evt_Dr_minDrLepJet',
    'Evt_Dr_minDrLepTag',
    'Evt_Dr_minDrTaggedJets',
    'Evt_E_JetsAverage',
    'Evt_E_TaggedJetsAverage',
    'Evt_Eta_JetsAverage',
    'Evt_Eta_TaggedJetsAverage',
    'Evt_HT',
    'Evt_HT_jets',
    'Evt_HT_tags',
    'Evt_HT_wo_MET',
    'Evt_JetPt_over_JetE',
    'Evt_M2_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_M2_closestTo125TaggedJets',
    'Evt_M2_closestTo91TaggedJets',
    'Evt_M2_minDrJets',
    'Evt_M2_minDrTaggedJets',
    'Evt_M3',
    'Evt_MET',
    'Evt_MET_Phi',
    'Evt_MET_Pt',
    'Evt_MHT',
    'Evt_MTW',
    'Evt_M_JetsAverage',
    'Evt_M_TaggedJetsAverage',
    'Evt_M_Total',
    'Evt_M_minDrLepJet',
    'Evt_M_minDrLepTag',
    'Evt_Pt_JetsAverage',
    'Evt_Pt_TaggedJetsAverage',
    'Evt_Pt_minDrJets',
    'Evt_Pt_minDrTaggedJets',
    'Evt_TaggedJetPt_over_TaggedJetE',
    'Evt_aplanarity',
    'Evt_aplanarity_jets',
    'Evt_aplanarity_tags',
    'Evt_blr',
    'Evt_blr_transformed',
    'Evt_btagValue_avg',
    'Evt_btagValue_avg_tagged',
    'Evt_btagValue_dev',
    'Evt_btagValue_dev_tagged',
    'Evt_btagValue_min',
    'Evt_btagValue_min_tagged',
    'Evt_h0',
    'Evt_h1',
    'Evt_h2',
    'Evt_h3',
    'Evt_sphericity',
    'Evt_sphericity_jets',
    'Evt_sphericity_tags',
    'Evt_transverse_sphericity',
    'Evt_transverse_sphericity_jets',
    'Evt_transverse_sphericity_tags',

    ]

chi2list_H = [
    "chi2H_ft_RecoX_X_Chi2",

    "chi2H_ft_RecoX_jet1_btagValue",
    "chi2H_ft_RecoX_jet2_btagValue",
    "chi2H_ft_RecoX_jet1_Pt",
    "chi2H_ft_RecoX_jet2_Pt",
    "chi2H_ft_RecoX_jet1_M",
    "chi2H_ft_RecoX_jet2_M",
    "chi2H_ft_RecoX_jet1_E",
    "chi2H_ft_RecoX_jet2_E",
    "chi2H_ft_RecoX_jet1_Eta",
    "chi2H_ft_RecoX_jet2_Eta",
    "chi2H_ft_RecoX_jet1_Phi",
    "chi2H_ft_RecoX_jet2_Phi",
    "chi2H_ft_RecoX_jet1_idx",
    "chi2H_ft_RecoX_jet2_idx",
    "chi2H_ft_RecoX_X_dPhi",
    "chi2H_ft_RecoX_X_dEta",
    "chi2H_ft_RecoX_X_dPt",
    "chi2H_ft_RecoX_X_dR",
    "chi2H_ft_RecoX_X_dKin",
    "chi2H_ft_RecoX_X_Pt",
    "chi2H_ft_RecoX_X_Eta",
    "chi2H_ft_RecoX_X_M",
    "chi2H_ft_RecoX_X_E",
    "chi2H_ft_RecoX_X_openingAngle",

    "chi2H_ft_RecoX_chi2",
    "chi2H_ft_RecoX_chi2log",
    "chi2H_ft_RecoX_chi2transformed",

    ]

chi2list_Z = [
    "chi2Z_ft_RecoX_X_Chi2",

    "chi2Z_ft_RecoX_jet1_btagValue",
    "chi2Z_ft_RecoX_jet2_btagValue",
    "chi2Z_ft_RecoX_jet1_Pt",
    "chi2Z_ft_RecoX_jet2_Pt",
    "chi2Z_ft_RecoX_jet1_M",
    "chi2Z_ft_RecoX_jet2_M",
    "chi2Z_ft_RecoX_jet1_E",
    "chi2Z_ft_RecoX_jet2_E",
    "chi2Z_ft_RecoX_jet1_Eta",
    "chi2Z_ft_RecoX_jet2_Eta",
    "chi2Z_ft_RecoX_jet1_Phi",
    "chi2Z_ft_RecoX_jet2_Phi",
    "chi2Z_ft_RecoX_jet1_idx",
    "chi2Z_ft_RecoX_jet2_idx",
    "chi2Z_ft_RecoX_X_dPhi",
    "chi2Z_ft_RecoX_X_dEta",
    "chi2Z_ft_RecoX_X_dPt",
    "chi2Z_ft_RecoX_X_dR",
    "chi2Z_ft_RecoX_X_dKin",
    "chi2Z_ft_RecoX_X_Pt",
    "chi2Z_ft_RecoX_X_Eta",
    "chi2Z_ft_RecoX_X_M",
    "chi2Z_ft_RecoX_X_E",
    "chi2Z_ft_RecoX_X_openingAngle",

    "chi2Z_ft_RecoX_chi2",
    "chi2Z_ft_RecoX_chi2log",
    "chi2Z_ft_RecoX_chi2transformed",

    ]

variables = {}
# for JAN_ttZ_ttH method
#variables["ge6j_ge3t"] = kinlist+recolist_Z+recolist_H+evtlist
#variables["ge4j_ge3t"] = kinlist+recolist_Z+recolist_H+evtlist

# for multiclassJAN method
#variables["ge6j_ge3t"] = kinlist+recolist_Z+recolist_H+recolist_cc+recolist_bb+recolist_ttTobb+evtlist
#variables["ge4j_ge3t"] = kinlist+recolist_Z+recolist_H+recolist_cc+recolist_bb+recolist_ttTobb+evtlist

# for multiclassJAN method  -  only reco-variables
variables["ge6j_ge3t"] = recolist_Z+recolist_H+recolist_cc+recolist_bb+recolist_ttTobb
variables["ge4j_ge3t"] = recolist_Z+recolist_H+recolist_cc+recolist_bb+recolist_ttTobb

#for chi^2-method
#variables["ge6j_ge3t"] = chi2list_Z+chi2list_H+evtlist+kinlist
#variables["ge4j_ge3t"] = chi2list_Z+chi2list_H+evtlist+kinlist

#for chi2_ttX_JAN_rest-method
#variables["ge6j_ge3t"] = kinlist+evtlist+chi2list_Z+chi2list_H+recolist_Z+recolist_H+recolist_cc+recolist_bb+recolist_ttTobb
#variables["ge4j_ge3t"] = kinlist+evtlist+chi2list_Z+chi2list_H+recolist_Z+recolist_H+recolist_cc+recolist_bb+recolist_ttTobb

#for chi2_ttX_JAN_rest-method
#variables["ge6j_ge3t"] = kinlist+evtlist+chi2list_Z+chi2list_H+recolist_cc+recolist_bb+recolist_ttTobb#+recolist_Z+recolist_H
#variables["ge4j_ge3t"] = kinlist+evtlist+chi2list_Z+chi2list_H+recolist_cc+recolist_bb+recolist_ttTobb#+recolist_Z+recolist_H


#for CNN without reco-variables
#variables["ge6j_ge3t"] = evtlist+kinlist#+chi2list_Z+chi2list_H+recolist_cc+recolist_bb+recolist_ttTobb#+recolist_Z+recolist_H
#variables["ge4j_ge3t"] = evtlist+kinlist#+chi2list_Z+chi2list_H+recolist_cc+recolist_bb+recolist_ttTobb#+recolist_Z+recolist_H

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
