variables = {}
variables["ge4j_ge3t"] = [
    "ttbarReco_HadTopB_Eta",
    "ttbarReco_HadTopB_Phi",
    "ttbarReco_HadTopB_CSV",
    "ttbarReco_HadTopB_M",
    "ttbarReco_HadTopB_E",
    "ttbarReco_HadTopB_Pt",
    "ttbarReco_HadTopB_idx",
    "ttbarReco_LepTopB_Eta",
    "ttbarReco_LepTopB_Phi",
    "ttbarReco_LepTopB_CSV",
    "ttbarReco_LepTopB_M",
    "ttbarReco_LepTopB_E",
    "ttbarReco_LepTopB_Pt",
    "ttbarReco_LepTopB_idx",
    "ttbarReco_HadTopQ1_Eta",
    "ttbarReco_HadTopQ1_Phi",
    "ttbarReco_HadTopQ1_CSV",
    "ttbarReco_HadTopQ1_M",
    "ttbarReco_HadTopQ1_E",
    "ttbarReco_HadTopQ1_Pt",
    "ttbarReco_HadTopQ1_idx",
    "ttbarReco_HadTopQ2_Eta",
    "ttbarReco_HadTopQ2_Phi",
    "ttbarReco_HadTopQ2_CSV",
    "ttbarReco_HadTopQ2_M",
    "ttbarReco_HadTopQ2_E",
    "ttbarReco_HadTopQ2_Pt",
    "ttbarReco_HadTopQ2_idx",
    "ttbarReco_ttbar_Pt",
    "ttbarReco_ttbar_Eta",
    "ttbarReco_ttbar_M",
    "ttbarReco_ttbar_E",
    "ttbarReco_ttbar_openingAngle", 
    "ttbarReco_LepTop_Pt",  
    "ttbarReco_LepTop_Eta", 
    "ttbarReco_LepTop_M",
    "ttbarReco_LepTop_E",
    "ttbarReco_LepTop_Phi",
    "ttbarReco_HadTop_Pt",
    "ttbarReco_HadTop_Eta",
    "ttbarReco_HadTop_M",
    "ttbarReco_HadTop_E",
    "ttbarReco_HadTop_Phi",
    "ttbarReco_ttbar_dPhi",
    "ttbarReco_ttbar_dEta",
    "ttbarReco_ttbar_dPt",
    "ttbarReco_ttbar_dR",
    "ttbarReco_ttbar_dKin",
    "N_Jets",
    "N_BTagsM",
    ] 
all_variables = list(set( [v for key in variables for v in variables[key] ] ))


