variables = {}
variables["ge4j_ge3t"] = [
    "bbfromttbar_HadTopB_Eta",
    "bbfromttbar_LepTopB_Eta",
    "bbfromttbar_HadTopB_Phi",
    "bbfromttbar_LepTopB_Phi",
    "bbfromttbar_HadTopB_CSV",
    "bbfromttbar_LepTopB_CSV",
    "bbfromttbar_HadTopB_M",
    "bbfromttbar_LepTopB_M",
    "bbfromttbar_HadTopB_E",
    "bbfromttbar_LepTopB_E",
    "bbfromttbar_HadTopB_Pt",
    "bbfromttbar_LepTopB_Pt",
    "bbfromttbar_HadTopB_idx",
    "bbfromttbar_LepTopB_idx",
    "TightLepton_Pt_0",
    "TightLepton_Eta_0",
    "TightLepton_Phi_0",
    "TightLepton_E_0",
    "Evt_MET_Pt",
    "Evt_MET_Phi",
    "bbfromttbar_HadTopBLepTopB_dPhi",
    "bbfromttbar_HadTopBLepTopB_dEta",
    "bbfromttbar_HadTopBLepTopB_dR",
    "bbfromttbar_HadTopBTightLepton_dPhi",
    "bbfromttbar_HadTopBTightLepton_dEta",
    "bbfromttbar_HadTopBTightLepton_dR",
    "bbfromttbar_LepTopBTightLepton_dPhi",
    "bbfromttbar_LepTopBTightLepton_dEta",
    "bbfromttbar_LepTopBTightLepton_dR",
    "bbfromttbar_LepTopBTightLepton_M",
    "bbfromttbar_HadTopBTightLepton_M",
    "N_Jets",
    "N_BTagsM",
    ] 
all_variables = list(set( [v for key in variables for v in variables[key] ] ))


