variables = {}

variables["5j_ge3t"] = [
    "Evt_Dr_minDrTaggedJets",
    "Evt_blr",
    "Evt_M2_TaggedJetsAverage",
    "Reco_LeptonicW_Pt",
    "CSV[2]",
    "Evt_CSV_avg_tagged",
    "Evt_JetPt_over_JetE",
    "Reco_ttH_h_dr",
    "RecoTTH_TopHad_W_Pt",
    "Evt_Dr_JetsAverage",
    "Evt_M2_closestTo91TaggedJets",
    "Reco_JABDT_ttH_tophad_pt__P__toplep_pt__P__h_pt__DIV__Evt_HT__P__Evt_Pt_MET__P__Lep_Pt",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_Deta_JetsAverage",
    "Evt_M2_minDrTaggedJets",
    "Evt_h1",
    "Reco_JABDT_ttH_Jet_CSV_whaddau2",
    "Reco_JABDT_ttH_Jet_CSV_btoplep",
    "Reco_JABDT_ttH_Jet_CSV_hdau1",
    "Reco_ttH_bestJABDToutput",
    "Evt_blr_transformed",
    "CSV[3]",
    "Evt_M2_JetsAverage",
    "RecoTTH_TopHad_M",
    "Evt_M_TaggedJetsAverage",
    "Evt_M_Total",
    "Evt_M_JetsAverage",
    "Evt_Pt_minDrTaggedJets",
    "Reco_JABDT_ttH_Jet_CSV_whaddau1",
    "Evt_CSV_avg",
    ]


variables["ge6j_ge3t"] = [
    "Reco_JABDT_ttH_Jet_CSV_hdau2",
    "Reco_ttH_tophad_pt",
    "Evt_M_minDrLepTag",
    "Evt_Dr_minDrTaggedJets",
    "Evt_CSV_min_tagged",
    "Jet_Pt[1]",
    "RecoTTH_Higgs_M",
    "TaggedJet_M[0]",
    "Evt_Deta_JetsAverage",
    "TaggedJet_Pt[0]",
    "Evt_blr",
    "Evt_M2_minDrTaggedJets",
    "Evt_M2_closestTo91TaggedJets",
    "CSV[4]",
    "Evt_M2_TaggedJetsAverage",
    "Evt_CSV_dev",
    "Jet_Pt[0]",
    "Evt_M_TaggedJetsAverage",
    "Reco_ttH_h_m",
    "Evt_Deta_TaggedJetsAverage",
    "Reco_JABDT_ttH_log_h_m",
    "CSV[3]",
    "Evt_CSV_avg",
    "Evt_Pt_minDrTaggedJets",
    "Evt_blr_transformed",
    "RecoTTH_Chi2Higgs",
    "Reco_ttH_bestJABDToutput",
    "CSV[2]",
    "Evt_M_JetsAverage",
    "Evt_Pt_JetsAverage",
    ]


variables["4j_ge3t"] = [
    "Evt_Dr_JetsAverage",
    "RecoTTH_TopHad_Pt",
    "Evt_M_JetsAverage",
    "CSV[3]",
    "Evt_CSV_min_tagged",
    "Reco_JABDT_ttH_Jet_CSV_whaddau1",
    "Reco_JABDT_ttH_log_tophad_m__M__whad_m",
    "Reco_JABDT_ttH_log_tophad_m",
    "Evt_Deta_JetsAverage",
    "Jet_M[0]",
    "Evt_blr_transformed",
    "Reco_JABDT_ttH_log_toplep_m",
    "Evt_Dr_minDrTaggedJets",
    "TaggedJet_M[0]",
    "Evt_CSV_avg_tagged",
    "Evt_CSV_dev",
    "Evt_CSV_min",
    "Reco_JABDT_ttH_Jet_CSV_whaddau2",
    "Evt_Pt_minDrTaggedJets",
    "Evt_Deta_TaggedJetsAverage",
    "CSV[2]",
    "Evt_M2_TaggedJetsAverage",
    "RecoTTH_TopLep_M",
    "Evt_HT",
    "Evt_M_Total",
    "Evt_HT_jets",
    "RecoTTH_Chi2Total",
    "RecoTTH_Chi2WHad",
    "RecoTTH_Chi2TopHad",
    "RecoTTH_TopHad_M",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
