variables = {}

variables["5j_ge3t"] = [
    "Reco_JABDT_ttH_log_h_pt",
    "Evt_CSV_min_tagged",
    "Evt_M2_TaggedJetsAverage",
    "Evt_aplanarity",
    "Reco_ttH_whad_pt",
    "Evt_Deta_JetsAverage",
    "Reco_JABDT_ttH_log_whad_m",
    "Evt_Dr_maxDrJets",
    "Reco_ttH_h_m",
    "Evt_CSV_avg_tagged",
    "Evt_MET",
    "CSV[2]",
    "Reco_ttH_hdau_idx2",
    "Evt_h1",
    "Evt_Dr_minDrTaggedJets",
    "Reco_JABDT_ttH_Jet_CSV_hdau2",
    "Reco_ttH_toplep_eta",
    "RecoTTH_TopHad_M",
    "Reco_ttH_hdau_idx1",
    "Reco_ttH_toplep_phi",
    "Evt_Deta_TaggedJetsAverage",
    "Reco_ttH_tophad_pt",
    "Evt_M_Total",
    "Reco_ttH_bestJABDToutput",
    "Reco_ttH_hdau_eta1",
    "Reco_JABDT_ttH_log_tophad_m",
    "Reco_JABDT_ttH_log_toplep_m",
    "Evt_M2_closestTo91TaggedJets",
    "Evt_M2_closestTo125TaggedJets",
    "Reco_LeptonicW_Pt",
    ]


variables["ge6j_ge3t"] = [
    "Jet_Pt[5]",
    "Reco_WLep_E",
    "Reco_JABDT_ttH_Jet_CSV_hdau2",
    "TaggedJet_E[0]",
    "Reco_ttH_tophad_pt",
    "Reco_JABDT_ttH_log_toplep_pt",
    "RecoTTH_Deta_Higgs_Lep",
    "Reco_ttH_whad_pt",
    "Jet_Pt[1]",
    "Evt_Dr_minDrTaggedJets",
    "Evt_HT_wo_MET",
    "Evt_M2_closestTo125TaggedJets",
    "CSV[2]",
    "Evt_M2_TaggedJetsAverage",
    "Evt_CSV_dev",
    "Evt_Pt_TaggedJetsAverage",
    "Evt_CSV_avg_tagged",
    "Jet_Pt[0]",
    "Evt_M_Total",
    "Evt_HT",
    "Evt_Deta_TaggedJetsAverage",
    "Reco_ttH_h_dr",
    "Reco_ttH_h_m",
    "Evt_blr",
    "Evt_M2_closestTo91TaggedJets",
    "RecoTTH_Higgs_M",
    "Evt_CSV_avg",
    "RecoTTH_Chi2Higgs",
    "Reco_JABDT_ttH_log_h_m",
    "Reco_ttH_bestJABDToutput",
    ]


variables["4j_ge3t"] = [
    "Reco_WLep_Mass",
    "RecoTTH_Dphi_topLep_bHad",
    "Reco_ttH_whaddau_eta1",
    "Evt_h1",
    "Reco_ttH_hdau_eta1",
    "Reco_JABDT_ttH_Jet_CSV_btoplep",
    "Evt_MHT",
    "Reco_ttH_tophad_m",
    "Reco_JABDT_ttH_Jet_CSV_whaddau2",
    "Evt_Deta_JetsAverage",
    "RecoTTH_Chi2TopHad",
    "RecoTTH_TopLep_M",
    "Jet_E[3]",
    "Reco_JABDT_ttH_Jet_CSV_hdau2",
    "Reco_ttH_whaddau_eta2",
    "Jet_CSV[0]",
    "Reco_ttH_whaddau_m2",
    "Reco_ttH_whad_eta",
    "Reco_ttH_hdau_idx2",
    "Reco_JABDT_ttH_log_toplep_pt",
    "Reco_ttH_hdau_m1",
    "Reco_JABDT_ttH_log_h_m",
    "Reco_ttH_hdau_m2",
    "Evt_M2_JetsAverage",
    "Reco_JABDT_ttH_log_tophad_m__M__whad_m",
    "Jet_Pt[1]",
    "Reco_ttH_h_phi",
    "Evt_M2_closestTo125TaggedJets",
    "Evt_M2_closestTo91TaggedJets",
    "Reco_ttH_hdau_eta2",
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
