python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_ttH_topVars -p -c ge4j_3t_0f -o tH_studies/final/02_ttH --netconfig tH --signalclass=ttH -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,ttH
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_ttH_topVars -p -c ge4j_ge4t_0f -o tH_studies/final/02_ttH --netconfig tH --signalclass=ttH -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,ttH
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_ttH_topVars -p -c ge3j_ge3t_ge1f -o tH_studies/final/02_ttH --netconfig tH --signalclass=ttH -e 2000 -a ttlf,ttcc,ttb_bb,tt2b,ttH
#python ../utils/getTopVariables.py -w ../workdir -i tH_studies/final/04-01_ttH_JTSTRING -o ../workdir/tH_studies/final/04-01_topVars -p -v --nvset 70 ge4j_3t_0f ge4j_ge4t_0f ge3j_ge3t_ge1f
#cp ../workdir/tH_studies/final/04-01_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_tH_topVars -p -c ge4j_3t_0f -o tH_studies/final/01_tH --netconfig	tH --signalclass=ttH,tH -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,ttH,tH
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_tH_topVars -p -c ge4j_ge4t_0f -o tH_studies/final/01_tH --netconfig	tH --signalclass=ttH,tH -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,ttH,tH
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_tH_topVars -p -c ge3j_ge3t_ge1f -o tH_studies/final/01_tH --netconfig	tH --signalclass=ttH,tH -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,ttH,tH
#python ../utils/getTopVariables.py -w ../workdir -i tH_studies/final/04-02_ttH_JTSTRING -o ../workdir/tH_studies/final/04-02_topVars -p -v --nvset 60 ge4j_3t_0f ge4j_ge4t_0f ge3j_ge3t_ge1f
#cp ../workdir/tH_studies/final/04-02_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_tHWtHQ_topVars -p -c ge4j_3t_0f -o tH_studies/final/03_tHQtHW --netconfig	tH --signalclass=ttH,tHQ,tHW -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,ttH,tHW,tHQ
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_tHWtHQ_topVars -p -c ge4j_ge4t_0f -o tH_studies/final/03_tHQtHW --netconfig	tH --signalclass=ttH,tHQ,tHW -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,ttH,tHW,tHQ
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_tHWtHQ_topVars -p -c ge3j_ge3t_ge1f -o tH_studies/final/03_tHQtHW --netconfig	tH --signalclass=ttH,tHQ,tHW -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,ttH,tHW,tHQ
#python ../utils/getTopVariables.py -w ../workdir -i tH_studies/final/04-03_ttH_JTSTRING -o ../workdir/tH_studies/final/04-03_topVars -p -v --nvset 50 ge4j_3t_0f ge4j_ge4t_0f ge3j_ge3t_ge1f
#cp ../workdir/tH_studies/final/04-03_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_t_ttH_topVars -p -c ge4j_3t_0f -o tH_studies/final/04_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,t_ttH
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_t_ttH_topVars -p -c ge4j_ge4t_0f -o tH_studies/final/04_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,t_ttH
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v 2017_t_ttH_topVars -p -c ge3j_ge3t_ge1f -o tH_studies/final/04_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,t_ttH
#python ../utils/getTopVariables.py -w ../workdir -i tH_studies/final/04-04_ttH_JTSTRING -o ../workdir/tH_studies/final/04-04_topVars -p -v --nvset 40 ge4j_3t_0f ge4j_ge4t
#cp ../workdir/tH_studies/final/04-04_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_3t_0f -o tH_studies/final/04-05_ttH --netconfig	tH --signalclass=ttH,tHQ,tHW -e 2000 -a ttlf,ttcc,ttb_bb,tt2b,ttH 
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_ge4t_0f -o tH_studies/final/04-05_ttH --netconfig	tH --signalclass=ttH,tHQ,tHW -e 2000  -a ttlf,ttcc,ttb_bb,tt2b,ttH
#python ../utils/getTopVariables.py -w ../workdir -i tH_studies/final/04-05_ttH_JTSTRING -o ../workdir/tH_studies/final/04-05_topVars -p -v --nvset 30 ge4j_3t_0f ge4j_ge4t -a ttlf,ttcc,ttb_bb,tt2b,ttH
#cp ../workdir/tH_studies/final/04-05_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_3t_0f -o tH_studies/final/04-06_ttH --netconfig	tH --signalclass=ttH,tHQ,tHW -e 2000 
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_ge4t_0f -o tH_studies/final/04-06_ttH --netconfig	tH --signalclass=ttH,tHQ,tHW -e 2000 
#python ../utils/getTopVariables.py -w ../workdir -i tH_studies/final/04-06_ttH_JTSTRING -o ../workdir/tH_studies/final/04-06_topVars -p -v --nvset 20 ge4j_3t_0f ge4j_ge4t
#cp ../workdir/tH_studies/final/04-05_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_3t_0f -o tH_studies/final/04-07_ttH --netconfig	tH --signalclass=ttH,tHQ,tHW -e 2000 
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_ge4t_0f -o tH_studies/final/04-07_ttH --netconfig	tH --signalclass=ttH,tHQ,tHW -e 2000 
