python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v legacy_2017_allVars -p -c ge4j_3t -o tH_noFWD/01-01_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v legacy_2017_allVars -p -c ge4j_ge4t -o tH_noFWD/01-01_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v legacy_2017_allVars -p -c ge3j_ge3t_ge1f -o tH_noFWD/01-01_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/01-01_t_ttH_JTSTRING -o ../workdir/tH_noFWD/01-01_topVars -p -v --nvset 70 ge4j_3t ge4j_ge4t
cp ../workdir/tH_noFWD/01-01_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_3t -o tH_noFWD/01-02_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/01-02_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge3j_ge3t_ge1f -o tH_noFWD/01-02_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/01-02_t_ttH_JTSTRING -o ../workdir/tH_noFWD/01-02_topVars -p -v --nvset 50 ge4j_3t ge4j_ge4t
cp ../workdir/tH_noFWD/01-02_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_3t -o tH_noFWD/01-03_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/01-03_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge3j_ge3t_ge1f -o tH_noFWD/01-03_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/01-03_t_ttH_JTSTRING -o ../workdir/tH_noFWD/01-03_topVars -p -v --nvset 40 ge4j_3t ge4j_ge4t
cp ../workdir/tH_noFWD/01-03_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_3t -o tH_noFWD/01-04_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/01-04_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
#python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/01-04_t_ttH_JTSTRING -o ../workdir/tH_noFWD/01-04_topVars -p -v --nvset 40 ge4j_3t ge4j_ge4t
#cp ../workdir/tH_noFWD/01-04_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_3t -o tH_noFWD/01-05_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/01-05_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
#python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/01-05_t_ttH_JTSTRING -o ../workdir/tH_noFWD/01-05_topVars -p -v --nvset 30 ge4j_3t ge4j_ge4t
#cp ../workdir/tH_noFWD/01-05_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_3t -o tH_noFWD/01-06_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/01-06_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
#python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/01-06_t_ttH_JTSTRING -o ../workdir/tH_noFWD/01-06_topVars -p -v --nvset 20 ge4j_3t ge4j_ge4t
#cp ../workdir/tH_noFWD/01-05_topVars/autogenerated_variableset.py ../variable_sets/tH_2017_vars.py
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_3t -o tH_noFWD/01-07_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
#python t_ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v tH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/01-07_t_ttH --netconfig	tH --signalclass=t_ttH -e 2000 
