python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v legacy_2017_allVars -p -c ge4j_3t -o tH_noFWD/03-01_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v legacy_2017_allVars -p -c ge4j_ge4t -o tH_noFWD/03-01_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v legacy_2017_allVars -p -c ge3j_ge3t_ge1f -o tH_noFWD/03-01_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/03-01_tH_JTSTRING -o ../workdir/tH_noFWD/03-01_topVars -p -v --nvset 70 ge4j_3t ge4j_ge4t
cp ../workdir/tH_noFWD/03-01_topVars/autogenerated_variableset.py ../variable_sets/extraTH_2017_vars.py
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_3t -o tH_noFWD/03-02_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/03-02_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge3j_ge3t_ge1f -o tH_noFWD/03-02_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/03-02_tH_JTSTRING -o ../workdir/tH_noFWD/03-02_topVars -p -v --nvset 50 ge4j_3t ge4j_ge4t
cp ../workdir/tH_noFWD/03-02_topVars/autogenerated_variableset.py ../variable_sets/extraTH_2017_vars.py
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_3t -o tH_noFWD/03-03_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/03-03_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge3j_ge3t_ge1f -o tH_noFWD/03-03_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/03-03_tH_JTSTRING -o ../workdir/tH_noFWD/03-03_topVars -p -v --nvset 40 ge4j_3t ge4j_ge4t
cp ../workdir/tH_noFWD/03-03_topVars/autogenerated_variableset.py ../variable_sets/extraTH_2017_vars.py
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_3t -o tH_noFWD/03-04_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/03-04_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
#python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/03-04_tH_JTSTRING -o ../workdir/tH_noFWD/03-04_topVars -p -v --nvset 40 ge4j_3t ge4j_ge4t
#cp ../workdir/tH_noFWD/03-04_topVars/autogenerated_variableset.py ../variable_sets/extraTH_2017_vars.py
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_3t -o tH_noFWD/03-05_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/03-05_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
#python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/03-05_tH_JTSTRING -o ../workdir/tH_noFWD/03-05_topVars -p -v --nvset 30 ge4j_3t ge4j_ge4t
#cp ../workdir/tH_noFWD/03-05_topVars/autogenerated_variableset.py ../variable_sets/extraTH_2017_vars.py
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_3t -o tH_noFWD/03-06_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/03-06_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
#python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/03-06_tH_JTSTRING -o ../workdir/tH_noFWD/03-06_topVars -p -v --nvset 20 ge4j_3t ge4j_ge4t
#cp ../workdir/tH_noFWD/03-05_topVars/autogenerated_variableset.py ../variable_sets/extraTH_2017_vars.py
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_3t -o tH_noFWD/03-07_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
#python tH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v extraTH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/03-07_tH --netconfig	tH --signalclass=ttH,tH -e 2000 
