python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v legacy_2017_allVars -p -c ge4j_3t -o tH_noFWD/02-01_ttH --netconfig	tH --signalclass=ttH -e 2000 
python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v legacy_2017_allVars -p -c ge4j_ge4t -o tH_noFWD/02-01_ttH --netconfig	tH --signalclass=ttH -e 2000 
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v legacy_2017_allVars -p -c ge3j_ge3t_ge1f -o tH_noFWD/02-01_ttH --netconfig	tH --signalclass=ttH -e 2000 
python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/02-01_ttH_JTSTRING -o ../workdir/tH_noFWD/02-01_topVars -p -v --nvset 70 ge4j_3t ge4j_ge4t
cp ../workdir/tH_noFWD/02-01_topVars/autogenerated_variableset.py ../variable_sets/ttH_2017_vars.py
python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_3t -o tH_noFWD/02-02_ttH --netconfig	tH --signalclass=ttH -e 2000 
python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/02-02_ttH --netconfig	tH --signalclass=ttH -e 2000 
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge3j_ge3t_ge1f -o tH_noFWD/02-02_ttH --netconfig	tH --signalclass=ttH -e 2000 
python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/02-02_ttH_JTSTRING -o ../workdir/tH_noFWD/02-02_topVars -p -v --nvset 50 ge4j_3t ge4j_ge4t
cp ../workdir/tH_noFWD/02-02_topVars/autogenerated_variableset.py ../variable_sets/ttH_2017_vars.py
python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_3t -o tH_noFWD/02-03_ttH --netconfig	tH --signalclass=ttH -e 2000 
python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/02-03_ttH --netconfig	tH --signalclass=ttH -e 2000 
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge3j_ge3t_ge1f -o tH_noFWD/02-03_ttH --netconfig	tH --signalclass=ttH -e 2000 
python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/02-03_ttH_JTSTRING -o ../workdir/tH_noFWD/02-03_topVars -p -v --nvset 40 ge4j_3t ge4j_ge4t
cp ../workdir/tH_noFWD/02-03_topVars/autogenerated_variableset.py ../variable_sets/ttH_2017_vars.py
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_3t -o tH_noFWD/02-04_ttH --netconfig	tH --signalclass=ttH -e 2000 
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/02-04_ttH --netconfig	tH --signalclass=ttH -e 2000 
#python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/02-04_ttH_JTSTRING -o ../workdir/tH_noFWD/02-04_topVars -p -v --nvset 40 ge4j_3t ge4j_ge4t
#cp ../workdir/tH_noFWD/02-04_topVars/autogenerated_variableset.py ../variable_sets/ttH_2017_vars.py
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_3t -o tH_noFWD/02-05_ttH --netconfig	tH --signalclass=ttH -e 2000 
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/02-05_ttH --netconfig	tH --signalclass=ttH -e 2000 
#python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/02-05_ttH_JTSTRING -o ../workdir/tH_noFWD/02-05_topVars -p -v --nvset 30 ge4j_3t ge4j_ge4t
#cp ../workdir/tH_noFWD/02-05_topVars/autogenerated_variableset.py ../variable_sets/ttH_2017_vars.py
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_3t -o tH_noFWD/02-06_ttH --netconfig	tH --signalclass=ttH -e 2000 
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/02-06_ttH --netconfig	tH --signalclass=ttH -e 2000 
#python ../utils/getTopVariables.py -w ../workdir -i tH_noFWD/02-06_ttH_JTSTRING -o ../workdir/tH_noFWD/02-06_topVars -p -v --nvset 20 ge4j_3t ge4j_ge4t
#cp ../workdir/tH_noFWD/02-05_topVars/autogenerated_variableset.py ../variable_sets/ttH_2017_vars.py
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_3t -o tH_noFWD/02-07_ttH --netconfig	tH --signalclass=ttH -e 2000 
#python ttH.py -i /local/scratch/hdd/pkraemer/legacy_2017_allVars -v ttH_2017_vars -p -c ge4j_ge4t -o tH_noFWD/02-07_ttH --netconfig	tH --signalclass=ttH -e 2000 
