#!/bin/bash

## only run from DRACO_MLfoy/utils
weight_type=propagated
topX=20
naming=bin_sp
for varset in allVars allVars_noReco RecoVarsOnly
do
    python getTopVariables.py -w ../workdir/ -i ${varset}/${naming}_v* -o ../variable_sets -v --nvset=$topX -p --nplot=$topX -t ${weight_type} 4j_ge3t 5j_ge3t ge6j_ge3t ge4j_3t ge4j_ge4t # le5j_3t ge6j_3t
    echo "rename variable set files"
    mv ../variable_sets/autogenerated_${weight_type}_variableset.py ../variable_sets/${varset}_bin_S01.py
    echo "move plots to workdir/${varset}"
    for figure in ../variable_sets/propagated_weight_sums*.pdf
    do
        mv ${figure} ../workdir/${varset}/${naming}_$(basename ${figure})
    done
    echo "done"
done


## only run from DRACO_MLfoy/utils
weight_type=propagated
topX=20
naming=sp
for varset in allVars allVars_noReco RecoVarsOnly
do
    python getTopVariables.py -w ../workdir/ -i ${varset}/${naming}_v* -o ../variable_sets -v --nvset=$topX -p --nplot=$topX -t ${weight_type} 4j_ge3t 5j_ge3t ge6j_ge3t ge4j_3t ge4j_ge4t # le5j_3t ge6j_3t
    echo "rename variable set files"
    mv ../variable_sets/autogenerated_${weight_type}_variableset.py ../variable_sets/${varset}_S01.py
    echo "move plots to workdir/${varset}"
    for figure in ../variable_sets/propagated_weight_sums*.pdf
    do
        mv ${figure} ../workdir/${varset}/${naming}_$(basename ${figure})
    done
    echo "done"
done
