#!/bin/bash

## only run from DRACO_MLfoy/utils
#weight_type=propagated
#topX=5
#naming=bin_sp
#for varset in allVars_noReco RecoVarsOnly
#do
#    python getTopVariables.py -w ../workdir/ -i ${varset}/${naming}_v* -o ../variable_sets -v --nvset=$topX -t ${weight_type} 4j_ge3t 5j_ge3t ge6j_ge3t ge4j_3t ge4j_ge4t # le5j_3t ge6j_3t
#    echo "rename variable set files"
#    mv ../variable_sets/autogenerated_${weight_type}_variableset.py ../variable_sets/${varset}_bin_S02.py
#    echo "done"
#done


## only run from DRACO_MLfoy/utils
weight_type=propagated
topX=30
naming=sp
for varset in topVariables_validated_decorr_2018vars #AngleFeaturesOnly_S01 #allVars_noReco RecoVarsOnly
do
    python getTopVariables.py -w ../workdir/ -i ${varset}/${naming}_v* -o ../variable_sets -t ${weight_type} -p 4j_ge3t 5j_ge3t ge6j_ge3t #ge4j_3t ge4j_ge4t # le5j_3t ge6j_3t
    echo "rename variable set files"
    mv ../variable_sets/autogenerated_${weight_type}_variableset.py ../variable_sets/${varset}_S02.py
    echo "done"
done
